/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    '/v3/attribution': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get CorpusLink spans and documents from a prompt */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description A GetAttributionRequest */
            requestBody: {
                content: {
                    'application/json': components['schemas']['GetAttributionRequest'];
                };
            };
            responses: {
                /** @description A AttributionResponse */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['AttributionResponse'];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v3/whoami': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get info for the current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A AuthenticatedClient */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['AuthenticatedClient'];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v4/admin/models/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get full details of a model */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A AdminModelResponse */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['AdminModelResponse'];
                    };
                };
            };
        };
        /** Reorder models */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description A ReorderModelConfigRequest */
            requestBody: {
                content: {
                    'application/json': components['schemas']['ReorderModelConfigRequest'];
                };
            };
            responses: {
                /** @description Empty Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Add a new model */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description A RootCreateModelConfigRequest */
            requestBody: {
                content: {
                    'application/json': components['schemas']['RootCreateModelConfigRequest'];
                };
            };
            responses: {
                /** @description A ResponseModel */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ResponseModel'];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v4/admin/models/{model_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a model */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    model_id: string;
                };
                cookie?: never;
            };
            /** @description A RootUpdateModelConfigRequest */
            requestBody: {
                content: {
                    'application/json': components['schemas']['RootUpdateModelConfigRequest'];
                };
            };
            responses: {
                /** @description A ResponseModel */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ResponseModel'];
                    };
                };
            };
        };
        post?: never;
        /** Delete a model */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    model_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Empty Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v4/agents/chat': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream a chat agent response */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description A AgentChatRequest */
            requestBody: {
                content: {
                    'application/json': components['schemas']['AgentChatRequest'];
                };
            };
            responses: {
                /** @description Empty Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v4/models/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get available models */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A ModelResponse */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ModelResponse'];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v4/prompt-templates/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get available prompt templates */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A PromptTemplateResponseList */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['PromptTemplateResponseList'];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v4/threads/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get messages */
        get: {
            parameters: {
                query?: {
                    offset?: number | null;
                    limit?: number;
                    sort?: string | null;
                    order?: components['schemas']['SortDirection'];
                    creator?: string | null;
                    deleted?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A GetThreadsResponse */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['GetThreadsResponse'];
                    };
                };
            };
        };
        put?: never;
        /** Stream a prompt response */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description A CreateMessageRequest */
            requestBody: {
                content: {
                    'application/json': components['schemas']['CreateMessageRequest'];
                };
            };
            responses: {
                /** @description Empty Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v4/threads/{thread_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get message */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    thread_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A Thread */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['Thread'];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v4/transcribe/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transcribe audio */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description A GetTranscriptionRequest */
            requestBody: {
                content: {
                    'multipart/form-data': components['schemas']['GetTranscriptionRequest'];
                };
            };
            responses: {
                /** @description A GetTranscriptionResponse */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['GetTranscriptionResponse'];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** AdminModelResponse */
        AdminModelResponse: components['schemas']['ResponseModel'][];
        /** AgentChatRequest */
        AgentChatRequest: {
            /** Agentid */
            agentId: string;
            /**
             * Bypasssafetycheck
             * @default false
             */
            bypassSafetyCheck?: boolean;
            /**
             * Captchatoken
             * @default null
             */
            captchaToken?: string | null;
            /** Content */
            content: string;
            /**
             * Maxsteps
             * @default null
             */
            maxSteps?: number | null;
            /**
             * Parent
             * @default null
             */
            parent?: string | null;
            /**
             * Template
             * @default null
             */
            template?: string | null;
        };
        /** AttributionDocumentSnippet */
        AttributionDocumentSnippet: {
            /** Corresponding Span Text */
            corresponding_span_text: string;
            /** Text */
            text: string;
        };
        /** AttributionResponse */
        AttributionResponse: {
            /** Documents */
            documents: components['schemas']['ResponseAttributionDocument'][];
            /** Index */
            index: string;
            /** Spans */
            spans: components['schemas']['TopLevelAttributionSpan'][];
        };
        /** AuthenticatedClient */
        AuthenticatedClient: {
            /** Client */
            client: string;
            /** Hasaccepteddatacollection */
            hasAcceptedDataCollection: boolean;
            /** Hasacceptedmediacollection */
            hasAcceptedMediaCollection: boolean;
            /** Hasacceptedtermsandconditions */
            hasAcceptedTermsAndConditions: boolean;
            /**
             * Id
             * @default null
             */
            id?: string | null;
            /** Permissions */
            permissions?: string[];
        };
        /**
         * AvailableInfiniGramIndexId
         * @enum {string}
         */
        AvailableInfiniGramIndexId:
            | 'olmoe-0125-1b-7b'
            | 'olmo-2-0325-32b'
            | 'olmo-2-1124-13b'
            | 'olmo-3-0625-32b-think'
            | 'olmo-3-0625-32b-instruct'
            | 'olmo-3-0625-7b-instruct'
            | 'olmo-3-0625-7b-think'
            | 'pileval-llama'
            | 'tulu-3-405b'
            | 'tulu-3-70b'
            | 'tulu-3-8b';
        /** AvailableTool */
        AvailableTool: {
            /**
             * Description
             * @default null
             */
            description?: string | null;
            /**
             * Mcpserverid
             * @default null
             */
            mcpServerId?: string | null;
            /** Name */
            name: string;
        };
        /** CreateMessageRequest */
        CreateMessageRequest: {
            /**
             * Bypasssafetycheck
             * @default false
             */
            bypassSafetyCheck?: boolean;
            /**
             * Captchatoken
             * @default null
             */
            captchaToken?: string | null;
            /**
             * Content
             * @default null
             */
            content?: string | null;
            /**
             * Enabletoolcalling
             * @default false
             */
            enableToolCalling?: boolean;
            /**
             * Extraparameters
             * @default null
             */
            extraParameters?: string | null;
            /**
             * Files
             * @default null
             */
            files?: string[] | null;
            /**
             * Host
             * @deprecated
             * @default null
             */
            host?: string | null;
            /**
             * Inputparts
             * @default null
             */
            inputParts?: string[] | null;
            /**
             * Logprobs
             * @default null
             */
            logprobs?: number | null;
            /**
             * Maxtokens
             * @default null
             */
            maxTokens?: number | null;
            /** Model */
            model: string;
            /**
             * N
             * @default 1
             */
            n?: number | null;
            /**
             * Original
             * @default null
             */
            original?: string | null;
            /**
             * Parent
             * @default null
             */
            parent?: string | null;
            /**
             * Private
             * @default false
             */
            private?: boolean;
            /** @default user */
            role?: components['schemas']['Role'] | null;
            /**
             * Selectedtools
             * @default null
             */
            selectedTools?: string[] | null;
            /** Stop */
            stop?: string[] | null;
            /**
             * Temperature
             * @default null
             */
            temperature?: number | null;
            /**
             * Template
             * @default null
             */
            template?: string | null;
            /**
             * Toolcallid
             * @default null
             */
            toolCallId?: string | null;
            /**
             * Tooldefinitions
             * @default null
             */
            toolDefinitions?: string | null;
            /**
             * Topp
             * @default null
             */
            topP?: number | null;
        };
        /** CreateMultiModalModelConfigRequest */
        CreateMultiModalModelConfigRequest: {
            /** Acceptedfiletypes */
            acceptedFileTypes: string[];
            /**
             * Allowfilesinfollowups
             * @default null
             */
            allowFilesInFollowups?: boolean | null;
            /**
             * Availabletime
             * @default null
             */
            availableTime?: string | null;
            /**
             * Cancalltools
             * @default false
             */
            canCallTools?: boolean;
            /**
             * Canthink
             * @default false
             */
            canThink?: boolean;
            /**
             * Defaultsystemprompt
             * @default null
             */
            defaultSystemPrompt?: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            deprecationTime?: string | null;
            /** Description */
            description: string;
            /**
             * Familyid
             * @default null
             */
            familyId?: string | null;
            /**
             * Familyname
             * @default null
             */
            familyName?: string | null;
            host: components['schemas']['ModelHost'];
            /** Id */
            id: string;
            /** @default null */
            infiniGramIndex?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /**
             * Informationurl
             * @default null
             */
            informationUrl?: string | null;
            /**
             * Internal
             * @default true
             */
            internal?: boolean;
            /**
             * Maxfilespermessage
             * @default null
             */
            maxFilesPerMessage?: number | null;
            /**
             * Maxtokensdefault
             * @default null
             */
            maxTokensDefault?: number | null;
            /**
             * Maxtokenslower
             * @default null
             */
            maxTokensLower?: number | null;
            /**
             * Maxtokensstep
             * @default null
             */
            maxTokensStep?: number | null;
            /**
             * Maxtokensupper
             * @default null
             */
            maxTokensUpper?: number | null;
            /**
             * Maxtotalfilesize
             * @default null
             */
            maxTotalFileSize?: string | number | null;
            /** Modelidonhost */
            modelIdOnHost: string;
            modelType: components['schemas']['ModelType'];
            /** Name */
            name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            promptType: 'files_only' | 'multi_modal';
            /** @default null */
            requireFileToPrompt?: components['schemas']['FileRequiredToPromptOption'] | null;
            /**
             * Stopdefault
             * @default null
             */
            stopDefault?: string[] | null;
            /**
             * Temperaturedefault
             * @default null
             */
            temperatureDefault?: number | null;
            /**
             * Temperaturelower
             * @default null
             */
            temperatureLower?: number | null;
            /**
             * Temperaturestep
             * @default null
             */
            temperatureStep?: number | null;
            /**
             * Temperatureupper
             * @default null
             */
            temperatureUpper?: number | null;
            /**
             * Toppdefault
             * @default null
             */
            topPDefault?: number | null;
            /**
             * Topplower
             * @default null
             */
            topPLower?: number | null;
            /**
             * Toppstep
             * @default null
             */
            topPStep?: number | null;
            /**
             * Toppupper
             * @default null
             */
            topPUpper?: number | null;
        };
        /** CreateTextOnlyModelConfigRequest */
        CreateTextOnlyModelConfigRequest: {
            /**
             * Availabletime
             * @default null
             */
            availableTime?: string | null;
            /**
             * Cancalltools
             * @default false
             */
            canCallTools?: boolean;
            /**
             * Canthink
             * @default false
             */
            canThink?: boolean;
            /**
             * Defaultsystemprompt
             * @default null
             */
            defaultSystemPrompt?: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            deprecationTime?: string | null;
            /** Description */
            description: string;
            /**
             * Familyid
             * @default null
             */
            familyId?: string | null;
            /**
             * Familyname
             * @default null
             */
            familyName?: string | null;
            host: components['schemas']['ModelHost'];
            /** Id */
            id: string;
            /** @default null */
            infiniGramIndex?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /**
             * Informationurl
             * @default null
             */
            informationUrl?: string | null;
            /**
             * Internal
             * @default true
             */
            internal?: boolean;
            /**
             * Maxtokensdefault
             * @default null
             */
            maxTokensDefault?: number | null;
            /**
             * Maxtokenslower
             * @default null
             */
            maxTokensLower?: number | null;
            /**
             * Maxtokensstep
             * @default null
             */
            maxTokensStep?: number | null;
            /**
             * Maxtokensupper
             * @default null
             */
            maxTokensUpper?: number | null;
            /** Modelidonhost */
            modelIdOnHost: string;
            modelType: components['schemas']['ModelType'];
            /** Name */
            name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            promptType: 'text_only';
            /**
             * Stopdefault
             * @default null
             */
            stopDefault?: string[] | null;
            /**
             * Temperaturedefault
             * @default null
             */
            temperatureDefault?: number | null;
            /**
             * Temperaturelower
             * @default null
             */
            temperatureLower?: number | null;
            /**
             * Temperaturestep
             * @default null
             */
            temperatureStep?: number | null;
            /**
             * Temperatureupper
             * @default null
             */
            temperatureUpper?: number | null;
            /**
             * Toppdefault
             * @default null
             */
            topPDefault?: number | null;
            /**
             * Topplower
             * @default null
             */
            topPLower?: number | null;
            /**
             * Toppstep
             * @default null
             */
            topPStep?: number | null;
            /**
             * Toppupper
             * @default null
             */
            topPUpper?: number | null;
        };
        /** CreateToolDefinition */
        CreateToolDefinition: {
            /** Description */
            description: string;
            /** Name */
            name: string;
            parameters: components['schemas']['ParameterDef'];
        };
        /** ErrorChunk */
        ErrorChunk: {
            errorCode: components['schemas']['ErrorCode'];
            /** Errordescription */
            errorDescription: string;
            /** @default error */
            errorSeverity?: components['schemas']['ErrorSeverity'];
            /** Message */
            message: string;
            /**
             * Type
             * @constant
             */
            readonly type: 'error';
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: 'toolCallError';
        /**
         * ErrorSeverity
         * @enum {string}
         */
        ErrorSeverity: 'error' | 'warning' | 'info';
        /**
         * FileRequiredToPromptOption
         * @enum {string}
         */
        FileRequiredToPromptOption: 'first_message' | 'all_messages' | 'no_requirement';
        /**
         * FinishReason
         * @enum {string}
         */
        FinishReason:
            | 'unclosed stream'
            | 'length'
            | 'stop'
            | 'aborted'
            | 'model overloaded'
            | 'bad connection'
            | 'value error'
            | 'tool error'
            | 'unknown';
        /** FlatMessage */
        FlatMessage: {
            /**
             * Agentid
             * @default null
             */
            agentId?: string | null;
            /**
             * Children
             * @default null
             */
            children?: string[] | null;
            /**
             * Completion
             * @default null
             */
            completion?: string | null;
            /** Content */
            content: string;
            /**
             * Created
             * Format: date-time
             */
            created: string;
            /** Creator */
            creator: string;
            /**
             * Deleted
             * @default null
             */
            deleted?: string | null;
            /** @default null */
            errorCode?: components['schemas']['ErrorCode'] | null;
            /**
             * Errordescription
             * @default null
             */
            errorDescription?: string | null;
            /** @default null */
            errorSeverity?: components['schemas']['ErrorSeverity'] | null;
            /**
             * Expirationtime
             * @default null
             */
            expirationTime?: string | null;
            /**
             * Extraparameters
             * @default null
             */
            extraParameters?: {
                [key: string]: unknown;
            } | null;
            /**
             * Fileurls
             * @default null
             */
            fileUrls?: string[] | null;
            /**
             * Final
             * @default false
             */
            final?: boolean;
            /** @default null */
            finishReason?: components['schemas']['FinishReason'] | null;
            /**
             * Harmful
             * @default null
             */
            harmful?: boolean | null;
            /** Id */
            id: string;
            /**
             * Inputparts
             * @default null
             */
            inputParts?: components['schemas']['Molmo2PointPart'][] | null;
            /** Islimitreached */
            readonly isLimitReached: boolean;
            /** Isolderthan30Days */
            readonly isOlderThan30Days: boolean;
            /** Labels */
            labels?: components['schemas']['LabelResponse'][];
            /** Modelhost */
            modelHost: string;
            /** Modelid */
            modelId: string;
            /** @default null */
            modelType?: components['schemas']['ModelType'] | null;
            opts: components['schemas']['InferenceOptionsResponse'];
            /**
             * Original
             * @default null
             */
            original?: string | null;
            /**
             * Parent
             * @default null
             */
            parent?: string | null;
            /**
             * Private
             * @default false
             */
            private?: boolean;
            role: components['schemas']['Role'];
            /** Root */
            root: string;
            /** Snippet */
            readonly snippet: string;
            /**
             * Template
             * @default null
             */
            template?: string | null;
            /**
             * Thinking
             * @default null
             */
            thinking?: string | null;
            /**
             * Toolcalls
             * @default null
             */
            toolCalls?: components['schemas']['ToolCall'][] | null;
            /**
             * Tooldefinitions
             * @default null
             */
            toolDefinitions?: components['schemas']['ToolDefinition'][] | null;
        };
        /** GetAttributionRequest */
        GetAttributionRequest: {
            /**
             * Maxdisplaycontextlength
             * @default 250
             */
            maxDisplayContextLength?: number;
            /**
             * Maxdocuments
             * @default 10
             */
            maxDocuments?: number;
            /** Modelid */
            modelId: string;
            /** Modelresponse */
            modelResponse: string;
            /** Prompt */
            prompt: string;
        };
        /** GetThreadsRequest */
        GetThreadsRequest: {
            /**
             * Creator
             * @default null
             */
            creator?: string | null;
            /**
             * Deleted
             * @default false
             */
            deleted?: boolean;
            /**
             * Limit
             * @default 10
             */
            limit?: number;
            /**
             * Offset
             * @default 0
             */
            offset?: number | null;
            /** @default DESC */
            order?: components['schemas']['SortDirection'];
            /**
             * Sort
             * @default null
             */
            sort?: string | null;
        };
        /** GetThreadsResponse */
        GetThreadsResponse: {
            meta: components['schemas']['ListMeta'];
            /** Threads */
            threads: components['schemas']['Thread'][];
        };
        /** GetTranscriptionRequest */
        GetTranscriptionRequest: {
            /**
             * Audio
             * Format: binary
             */
            audio: string;
        };
        /** GetTranscriptionResponse */
        GetTranscriptionResponse: {
            /** Text */
            text: string;
        };
        /** InferenceOptionsResponse */
        InferenceOptionsResponse: {
            /**
             * Logprobs
             * @default null
             */
            logprobs?: number | null;
            /**
             * Maxtokens
             * @default null
             */
            maxTokens?: number | null;
            /**
             * N
             * @default 1
             */
            n?: number;
            /**
             * Stop
             * @default null
             */
            stop?: string[] | null;
            /**
             * Temperature
             * @default null
             */
            temperature?: number | null;
            /**
             * Topp
             * @default null
             */
            topP?: number | null;
        };
        /** LabelResponse */
        LabelResponse: {
            /**
             * Comment
             * @default null
             */
            comment?: string | null;
            /**
             * Created
             * Format: date-time
             */
            created: string;
            /** Creator */
            creator: string;
            /**
             * Deleted
             * @default null
             */
            deleted?: string | null;
            /** Id */
            id: string;
            /** Message */
            message: string;
            rating: components['schemas']['Rating'];
        };
        /** ListMeta */
        ListMeta: {
            /**
             * Limit
             * @default null
             */
            limit?: number | null;
            /**
             * Offset
             * @default null
             */
            offset?: number | null;
            /** @default null */
            sort?: components['schemas']['Sort'] | null;
            /** Total */
            total: number;
        };
        /** Model */
        Model: {
            /**
             * Accepts Files
             * @default false
             */
            accepts_files?: boolean;
            /**
             * Available Tools
             * @default null
             */
            available_tools?: components['schemas']['AvailableTool'][] | null;
            /**
             * Can Call Tools
             * @default false
             */
            can_call_tools?: boolean;
            /**
             * Can Think
             * @default false
             */
            can_think?: boolean;
            /** Description */
            description: string;
            /**
             * Family Id
             * @default null
             */
            family_id?: string | null;
            /**
             * Family Name
             * @default null
             */
            family_name?: string | null;
            host: components['schemas']['ModelHost'];
            /** Id */
            id: string;
            /** @default null */
            infini_gram_index?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /**
             * Information Url
             * @default null
             */
            information_url?: string | null;
            /** Internal */
            internal: boolean;
            /** Is Deprecated */
            readonly is_deprecated: boolean;
            /** Is Visible */
            readonly is_visible: boolean;
            /**
             * Max Tokens Default
             * @default null
             */
            max_tokens_default?: number | null;
            /**
             * Max Tokens Lower
             * @default null
             */
            max_tokens_lower?: number | null;
            /**
             * Max Tokens Step
             * @default null
             */
            max_tokens_step?: number | null;
            /**
             * Max Tokens Upper
             * @default null
             */
            max_tokens_upper?: number | null;
            model_type: components['schemas']['ModelType'];
            /** Name */
            name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            prompt_type: 'text_only';
            /**
             * Stop Default
             * @default null
             */
            stop_default?: string[] | null;
            /**
             * System Prompt
             * @default null
             */
            system_prompt?: string | null;
            /**
             * Temperature Default
             * @default null
             */
            temperature_default?: number | null;
            /**
             * Temperature Lower
             * @default null
             */
            temperature_lower?: number | null;
            /**
             * Temperature Step
             * @default null
             */
            temperature_step?: number | null;
            /**
             * Temperature Upper
             * @default null
             */
            temperature_upper?: number | null;
            /**
             * Top P Default
             * @default null
             */
            top_p_default?: number | null;
            /**
             * Top P Lower
             * @default null
             */
            top_p_lower?: number | null;
            /**
             * Top P Step
             * @default null
             */
            top_p_step?: number | null;
            /**
             * Top P Upper
             * @default null
             */
            top_p_upper?: number | null;
        };
        /**
         * ModelAvailability
         * @enum {string}
         */
        ModelAvailability: 'public' | 'internal' | 'prerelease';
        /**
         * ModelHost
         * @enum {string}
         */
        ModelHost:
            | 'inferd'
            | 'modal'
            | 'beaker_queues'
            | 'cirrascale_backend'
            | 'cirrascale'
            | 'modal_openai'
            | 'test_backend'
            | 'ai2_model_hub';
        /** ModelOrder */
        ModelOrder: {
            /** Id */
            id: string;
            /** Order */
            order: number;
        };
        /** ModelResponse */
        ModelResponse: (
            | components['schemas']['Model']
            | components['schemas']['MultiModalModel']
        )[];
        /** ModelResponseChunk */
        ModelResponseChunk: {
            /** Content */
            content: string;
            /** Message */
            message: string;
            /**
             * Type
             * @constant
             */
            readonly type: 'modelResponse';
        };
        /**
         * ModelType
         * @enum {string}
         */
        ModelType: 'base' | 'chat';
        /** Molmo2PointPart */
        Molmo2PointPart: {
            /**
             * Label
             * @default object
             */
            label?: string;
            /** Time */
            time: number;
            /**
             * Type
             * @default molmo_2_input_point
             * @constant
             */
            type?: 'molmo_2_input_point';
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** MultiModalModel */
        MultiModalModel: {
            /**
             * Accepted File Types
             * @description A list of file type specifiers: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#unique_file_type_specifiers
             */
            accepted_file_types: string[];
            /**
             * Accepts Files
             * @default true
             */
            accepts_files?: boolean;
            /**
             * Allow Files In Followups
             * @description Defines if a user is allowed to send files with follow-up prompts. To require a file to prompt, use require_file_to_prompt
             * @default false
             */
            allow_files_in_followups?: boolean;
            /**
             * Available Tools
             * @default null
             */
            available_tools?: components['schemas']['AvailableTool'][] | null;
            /**
             * Can Call Tools
             * @default false
             */
            can_call_tools?: boolean;
            /**
             * Can Think
             * @default false
             */
            can_think?: boolean;
            /** Description */
            description: string;
            /**
             * Family Id
             * @default null
             */
            family_id?: string | null;
            /**
             * Family Name
             * @default null
             */
            family_name?: string | null;
            host: components['schemas']['ModelHost'];
            /** Id */
            id: string;
            /** @default null */
            infini_gram_index?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /**
             * Information Url
             * @default null
             */
            information_url?: string | null;
            /** Internal */
            internal: boolean;
            /** Is Deprecated */
            readonly is_deprecated: boolean;
            /** Is Visible */
            readonly is_visible: boolean;
            /**
             * Max Files Per Message
             * @description The maximum number of files the user is allowed to send with a message
             * @default null
             */
            max_files_per_message?: number | null;
            /**
             * Max Tokens Default
             * @default null
             */
            max_tokens_default?: number | null;
            /**
             * Max Tokens Lower
             * @default null
             */
            max_tokens_lower?: number | null;
            /**
             * Max Tokens Step
             * @default null
             */
            max_tokens_step?: number | null;
            /**
             * Max Tokens Upper
             * @default null
             */
            max_tokens_upper?: number | null;
            /**
             * Max Total File Size
             * @description The maximum total file size a user is allowed to send. Adds up the size of every file.
             * @default null
             */
            max_total_file_size?: number | null;
            model_type: components['schemas']['ModelType'];
            /** Name */
            name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            prompt_type: 'files_only' | 'multi_modal';
            /**
             * @description Defines if a user is required to send files with messages. Not intended to prevent users from sending files with follow-up messages.
             * @default no_requirement
             */
            require_file_to_prompt?: components['schemas']['FileRequiredToPromptOption'];
            /**
             * Stop Default
             * @default null
             */
            stop_default?: string[] | null;
            /**
             * System Prompt
             * @default null
             */
            system_prompt?: string | null;
            /**
             * Temperature Default
             * @default null
             */
            temperature_default?: number | null;
            /**
             * Temperature Lower
             * @default null
             */
            temperature_lower?: number | null;
            /**
             * Temperature Step
             * @default null
             */
            temperature_step?: number | null;
            /**
             * Temperature Upper
             * @default null
             */
            temperature_upper?: number | null;
            /**
             * Top P Default
             * @default null
             */
            top_p_default?: number | null;
            /**
             * Top P Lower
             * @default null
             */
            top_p_lower?: number | null;
            /**
             * Top P Step
             * @default null
             */
            top_p_step?: number | null;
            /**
             * Top P Upper
             * @default null
             */
            top_p_upper?: number | null;
        };
        /** MultiModalResponseModel */
        MultiModalResponseModel: {
            /** Acceptedfiletypes */
            acceptedFileTypes: string[];
            /**
             * Allowfilesinfollowups
             * @default null
             */
            allowFilesInFollowups?: boolean | null;
            readonly availability: components['schemas']['ModelAvailability'];
            /**
             * Availabletime
             * @default null
             */
            availableTime?: string | null;
            /** Cancalltools */
            canCallTools: boolean;
            /** Canthink */
            canThink: boolean;
            /**
             * Createdtime
             * Format: date-time
             */
            createdTime: string;
            /**
             * Defaultsystemprompt
             * @default null
             */
            defaultSystemPrompt?: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            deprecationTime?: string | null;
            /** Description */
            description: string;
            /**
             * Familyid
             * @default null
             */
            familyId?: string | null;
            /**
             * Familyname
             * @default null
             */
            familyName?: string | null;
            host: components['schemas']['ModelHost'];
            /** Id */
            id: string;
            /** @default null */
            infiniGramIndex?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /**
             * Informationurl
             * @default null
             */
            informationUrl?: string | null;
            /** Internal */
            internal: boolean;
            /**
             * Maxfilespermessage
             * @default null
             */
            maxFilesPerMessage?: number | null;
            /** Maxtokensdefault */
            maxTokensDefault: number;
            /** Maxtokenslower */
            maxTokensLower: number;
            /** Maxtokensstep */
            maxTokensStep: number;
            /** Maxtokensupper */
            maxTokensUpper: number;
            /**
             * Maxtotalfilesize
             * @default null
             */
            maxTotalFileSize?: number | null;
            /** Modelidonhost */
            modelIdOnHost: string;
            modelType: components['schemas']['ModelType'];
            /** Name */
            name: string;
            /** Order */
            order: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            promptType: 'files_only' | 'multi_modal';
            /** @default null */
            requireFileToPrompt?: components['schemas']['FileRequiredToPromptOption'] | null;
            /**
             * Stopdefault
             * @default null
             */
            stopDefault?: string[] | null;
            /** Temperaturedefault */
            temperatureDefault: number;
            /** Temperaturelower */
            temperatureLower: number;
            /** Temperaturestep */
            temperatureStep: number;
            /** Temperatureupper */
            temperatureUpper: number;
            /** Toppdefault */
            topPDefault: number;
            /** Topplower */
            topPLower: number;
            /** Toppstep */
            topPStep: number;
            /** Toppupper */
            topPUpper: number;
            /**
             * Updatedtime
             * Format: date-time
             */
            updatedTime: string;
        };
        /** ParameterDef */
        ParameterDef: {
            /**
             * Default
             * @default null
             */
            default?: {
                [key: string]: string;
            } | null;
            /**
             * Description
             * @default null
             */
            description?: string | null;
            /**
             * Properties
             * @default null
             */
            properties?: {
                [key: string]: components['schemas']['ParameterDef'];
            } | null;
            /**
             * Propertyordering
             * @default null
             */
            propertyOrdering?: string[] | null;
            /**
             * Required
             * @default []
             */
            required?: string[] | null;
            /** Type */
            type: string;
        };
        /** PromptTemplateResponse */
        PromptTemplateResponse: {
            /** Content */
            content: string;
            /**
             * Created
             * Format: date-time
             */
            created: string;
            /** Creator */
            creator: string;
            /**
             * Extraparameters
             * @default null
             */
            extraParameters?: {
                [key: string]: unknown;
            } | null;
            /** Fileurls */
            fileUrls: string[] | null;
            /** Id */
            id: string;
            modelType: components['schemas']['ModelType'];
            /** Name */
            name: string;
            opts: components['schemas']['InferenceOptionsResponse'];
            /** Tooldefinitions */
            toolDefinitions: components['schemas']['ToolDefinition'][];
            /**
             * Updated
             * Format: date-time
             */
            updated: string;
        };
        /** PromptTemplateResponseList */
        PromptTemplateResponseList: components['schemas']['PromptTemplateResponse'][];
        /**
         * Rating
         * @enum {integer}
         */
        Rating: -1 | 0 | 1;
        /** ReorderModelConfigRequest */
        ReorderModelConfigRequest: {
            /** Orderedmodels */
            orderedModels: components['schemas']['ModelOrder'][];
        };
        /** ResponseAttributionDocument */
        ResponseAttributionDocument: {
            /** Corresponding Span Texts */
            corresponding_span_texts: string[];
            /** Corresponding Spans */
            corresponding_spans: number[];
            /** Display Name */
            display_name: string | null;
            /** Index */
            index: string;
            /** Relevance Score */
            relevance_score: number;
            /**
             * Secondary Name
             * @default null
             */
            secondary_name?: string | null;
            /** Snippets */
            snippets: components['schemas']['AttributionDocumentSnippet'][];
            /** Source */
            source: string | null;
            /** Source Url */
            source_url: string | null;
            /** Text Long */
            text_long: string;
            /**
             * Title
             * @default null
             */
            title?: string | null;
            /**
             * Url
             * @default null
             */
            url?: string | null;
            /** Usage */
            usage: string | null;
        };
        /** ResponseAttributionSpan */
        ResponseAttributionSpan: {
            /** Documents */
            documents?: number[];
            /** Start Index */
            start_index: number;
            /** Text */
            text: string;
        };
        /** ResponseModel */
        ResponseModel:
            | components['schemas']['TextOnlyResponseModel']
            | components['schemas']['MultiModalResponseModel'];
        /**
         * Role
         * @enum {string}
         */
        Role: 'user' | 'assistant' | 'system' | 'tool_call_result';
        /** RootCreateModelConfigRequest */
        RootCreateModelConfigRequest:
            | components['schemas']['CreateTextOnlyModelConfigRequest']
            | components['schemas']['CreateMultiModalModelConfigRequest'];
        /** RootUpdateModelConfigRequest */
        RootUpdateModelConfigRequest:
            | components['schemas']['UpdateTextOnlyModelConfigRequest']
            | components['schemas']['UpdateMultiModalModelConfigRequest'];
        /** Sort */
        Sort: {
            /** @default DESC */
            direction?: components['schemas']['SortDirection'];
            /** Field */
            field: string;
        };
        /**
         * SortDirection
         * @enum {string}
         */
        SortDirection: 'ASC' | 'DESC';
        /** StreamEndChunk */
        StreamEndChunk: {
            /** Message */
            message: string;
            /**
             * Type
             * @constant
             */
            readonly type: 'end';
        };
        /** StreamStartChunk */
        StreamStartChunk: {
            /** Message */
            message: string;
            /**
             * Type
             * @constant
             */
            readonly type: 'start';
        };
        /** TextOnlyResponseModel */
        TextOnlyResponseModel: {
            readonly availability: components['schemas']['ModelAvailability'];
            /**
             * Availabletime
             * @default null
             */
            availableTime?: string | null;
            /** Cancalltools */
            canCallTools: boolean;
            /** Canthink */
            canThink: boolean;
            /**
             * Createdtime
             * Format: date-time
             */
            createdTime: string;
            /**
             * Defaultsystemprompt
             * @default null
             */
            defaultSystemPrompt?: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            deprecationTime?: string | null;
            /** Description */
            description: string;
            /**
             * Familyid
             * @default null
             */
            familyId?: string | null;
            /**
             * Familyname
             * @default null
             */
            familyName?: string | null;
            host: components['schemas']['ModelHost'];
            /** Id */
            id: string;
            /** @default null */
            infiniGramIndex?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /**
             * Informationurl
             * @default null
             */
            informationUrl?: string | null;
            /** Internal */
            internal: boolean;
            /** Maxtokensdefault */
            maxTokensDefault: number;
            /** Maxtokenslower */
            maxTokensLower: number;
            /** Maxtokensstep */
            maxTokensStep: number;
            /** Maxtokensupper */
            maxTokensUpper: number;
            /** Modelidonhost */
            modelIdOnHost: string;
            modelType: components['schemas']['ModelType'];
            /** Name */
            name: string;
            /** Order */
            order: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            promptType: 'text_only';
            /**
             * Stopdefault
             * @default null
             */
            stopDefault?: string[] | null;
            /** Temperaturedefault */
            temperatureDefault: number;
            /** Temperaturelower */
            temperatureLower: number;
            /** Temperaturestep */
            temperatureStep: number;
            /** Temperatureupper */
            temperatureUpper: number;
            /** Toppdefault */
            topPDefault: number;
            /** Topplower */
            topPLower: number;
            /** Toppstep */
            topPStep: number;
            /** Toppupper */
            topPUpper: number;
            /**
             * Updatedtime
             * Format: date-time
             */
            updatedTime: string;
        };
        /** ThinkingChunk */
        ThinkingChunk: {
            /** Content */
            content: string;
            /**
             * Id
             * @default null
             */
            id?: string | null;
            /** Message */
            message: string;
            /**
             * Type
             * @constant
             */
            readonly type: 'thinking';
        };
        /** Thread */
        Thread: {
            /** Id */
            id: string;
            /** Messages */
            messages: components['schemas']['FlatMessage'][];
        };
        /** ToolCall */
        ToolCall: {
            /**
             * Args
             * @default null
             */
            args?:
                | string
                | {
                      [key: string]: unknown;
                  }
                | null;
            /** Toolcallid */
            toolCallId: string;
            /** Toolname */
            toolName: string;
            toolSource: components['schemas']['ToolSource'];
        };
        /** ToolCallChunk */
        ToolCallChunk: {
            /**
             * Args
             * @default null
             */
            args?:
                | string
                | {
                      [key: string]: unknown;
                  }
                | null;
            /** Message */
            message: string;
            /** Toolcallid */
            toolCallId: string;
            /** Toolname */
            toolName: string;
            toolSource: components['schemas']['ToolSource'] | null;
            /**
             * Type
             * @constant
             */
            readonly type: 'toolCall';
        };
        /** ToolDefinition */
        ToolDefinition: {
            /** Description */
            description: string;
            /** Name */
            name: string;
            /**
             * Parameters
             * @default null
             */
            parameters?: {
                [key: string]: unknown;
            } | null;
            toolSource: components['schemas']['ToolSource'];
        };
        /**
         * ToolSource
         * @enum {string}
         */
        ToolSource: 'internal' | 'user_defined' | 'model_context_protocol';
        /** TopLevelAttributionSpan */
        TopLevelAttributionSpan: {
            /** Documents */
            documents?: number[];
            /** Nested Spans */
            nested_spans?: components['schemas']['ResponseAttributionSpan'][];
            /** Start Index */
            start_index: number;
            /** Text */
            text: string;
        };
        /** UpdateMultiModalModelConfigRequest */
        UpdateMultiModalModelConfigRequest: {
            /** Acceptedfiletypes */
            acceptedFileTypes: string[];
            /**
             * Allowfilesinfollowups
             * @default null
             */
            allowFilesInFollowups?: boolean | null;
            /**
             * Availabletime
             * @default null
             */
            availableTime?: string | null;
            /**
             * Cancalltools
             * @default false
             */
            canCallTools?: boolean;
            /**
             * Canthink
             * @default false
             */
            canThink?: boolean;
            /**
             * Defaultsystemprompt
             * @default null
             */
            defaultSystemPrompt?: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            deprecationTime?: string | null;
            /** Description */
            description: string;
            /**
             * Familyid
             * @default null
             */
            familyId?: string | null;
            /**
             * Familyname
             * @default null
             */
            familyName?: string | null;
            host: components['schemas']['ModelHost'];
            /** @default null */
            infiniGramIndex?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /**
             * Informationurl
             * @default null
             */
            informationUrl?: string | null;
            /**
             * Internal
             * @default true
             */
            internal?: boolean;
            /**
             * Maxfilespermessage
             * @default null
             */
            maxFilesPerMessage?: number | null;
            /**
             * Maxtokensdefault
             * @default null
             */
            maxTokensDefault?: number | null;
            /**
             * Maxtokenslower
             * @default null
             */
            maxTokensLower?: number | null;
            /**
             * Maxtokensstep
             * @default null
             */
            maxTokensStep?: number | null;
            /**
             * Maxtokensupper
             * @default null
             */
            maxTokensUpper?: number | null;
            /**
             * Maxtotalfilesize
             * @default null
             */
            maxTotalFileSize?: string | number | null;
            /** Modelidonhost */
            modelIdOnHost: string;
            modelType: components['schemas']['ModelType'];
            /** Name */
            name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            promptType: 'files_only' | 'multi_modal';
            /** @default null */
            requireFileToPrompt?: components['schemas']['FileRequiredToPromptOption'] | null;
            /**
             * Stopdefault
             * @default null
             */
            stopDefault?: string[] | null;
            /**
             * Temperaturedefault
             * @default null
             */
            temperatureDefault?: number | null;
            /**
             * Temperaturelower
             * @default null
             */
            temperatureLower?: number | null;
            /**
             * Temperaturestep
             * @default null
             */
            temperatureStep?: number | null;
            /**
             * Temperatureupper
             * @default null
             */
            temperatureUpper?: number | null;
            /**
             * Toppdefault
             * @default null
             */
            topPDefault?: number | null;
            /**
             * Topplower
             * @default null
             */
            topPLower?: number | null;
            /**
             * Toppstep
             * @default null
             */
            topPStep?: number | null;
            /**
             * Toppupper
             * @default null
             */
            topPUpper?: number | null;
        };
        /** UpdateTextOnlyModelConfigRequest */
        UpdateTextOnlyModelConfigRequest: {
            /**
             * Availabletime
             * @default null
             */
            availableTime?: string | null;
            /**
             * Cancalltools
             * @default false
             */
            canCallTools?: boolean;
            /**
             * Canthink
             * @default false
             */
            canThink?: boolean;
            /**
             * Defaultsystemprompt
             * @default null
             */
            defaultSystemPrompt?: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            deprecationTime?: string | null;
            /** Description */
            description: string;
            /**
             * Familyid
             * @default null
             */
            familyId?: string | null;
            /**
             * Familyname
             * @default null
             */
            familyName?: string | null;
            host: components['schemas']['ModelHost'];
            /** @default null */
            infiniGramIndex?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /**
             * Informationurl
             * @default null
             */
            informationUrl?: string | null;
            /**
             * Internal
             * @default true
             */
            internal?: boolean;
            /**
             * Maxtokensdefault
             * @default null
             */
            maxTokensDefault?: number | null;
            /**
             * Maxtokenslower
             * @default null
             */
            maxTokensLower?: number | null;
            /**
             * Maxtokensstep
             * @default null
             */
            maxTokensStep?: number | null;
            /**
             * Maxtokensupper
             * @default null
             */
            maxTokensUpper?: number | null;
            /** Modelidonhost */
            modelIdOnHost: string;
            modelType: components['schemas']['ModelType'];
            /** Name */
            name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            promptType: 'text_only';
            /**
             * Stopdefault
             * @default null
             */
            stopDefault?: string[] | null;
            /**
             * Temperaturedefault
             * @default null
             */
            temperatureDefault?: number | null;
            /**
             * Temperaturelower
             * @default null
             */
            temperatureLower?: number | null;
            /**
             * Temperaturestep
             * @default null
             */
            temperatureStep?: number | null;
            /**
             * Temperatureupper
             * @default null
             */
            temperatureUpper?: number | null;
            /**
             * Toppdefault
             * @default null
             */
            topPDefault?: number | null;
            /**
             * Topplower
             * @default null
             */
            topPLower?: number | null;
            /**
             * Toppstep
             * @default null
             */
            topPStep?: number | null;
            /**
             * Toppupper
             * @default null
             */
            topPUpper?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type SchemaAdminModelResponse = components['schemas']['AdminModelResponse'];
export type SchemaAgentChatRequest = components['schemas']['AgentChatRequest'];
export type SchemaAttributionDocumentSnippet = components['schemas']['AttributionDocumentSnippet'];
export type SchemaAttributionResponse = components['schemas']['AttributionResponse'];
export type SchemaAuthenticatedClient = components['schemas']['AuthenticatedClient'];
export type SchemaAvailableInfiniGramIndexId = components['schemas']['AvailableInfiniGramIndexId'];
export type SchemaAvailableTool = components['schemas']['AvailableTool'];
export type SchemaCreateMessageRequest = components['schemas']['CreateMessageRequest'];
export type SchemaCreateMultiModalModelConfigRequest =
    components['schemas']['CreateMultiModalModelConfigRequest'];
export type SchemaCreateTextOnlyModelConfigRequest =
    components['schemas']['CreateTextOnlyModelConfigRequest'];
export type SchemaCreateToolDefinition = components['schemas']['CreateToolDefinition'];
export type SchemaErrorChunk = components['schemas']['ErrorChunk'];
export type SchemaErrorCode = components['schemas']['ErrorCode'];
export type SchemaErrorSeverity = components['schemas']['ErrorSeverity'];
export type SchemaFileRequiredToPromptOption = components['schemas']['FileRequiredToPromptOption'];
export type SchemaFinishReason = components['schemas']['FinishReason'];
export type SchemaFlatMessage = components['schemas']['FlatMessage'];
export type SchemaGetAttributionRequest = components['schemas']['GetAttributionRequest'];
export type SchemaGetThreadsRequest = components['schemas']['GetThreadsRequest'];
export type SchemaGetThreadsResponse = components['schemas']['GetThreadsResponse'];
export type SchemaGetTranscriptionRequest = components['schemas']['GetTranscriptionRequest'];
export type SchemaGetTranscriptionResponse = components['schemas']['GetTranscriptionResponse'];
export type SchemaInferenceOptionsResponse = components['schemas']['InferenceOptionsResponse'];
export type SchemaLabelResponse = components['schemas']['LabelResponse'];
export type SchemaListMeta = components['schemas']['ListMeta'];
export type SchemaModel = components['schemas']['Model'];
export type SchemaModelAvailability = components['schemas']['ModelAvailability'];
export type SchemaModelHost = components['schemas']['ModelHost'];
export type SchemaModelOrder = components['schemas']['ModelOrder'];
export type SchemaModelResponse = components['schemas']['ModelResponse'];
export type SchemaModelResponseChunk = components['schemas']['ModelResponseChunk'];
export type SchemaModelType = components['schemas']['ModelType'];
export type SchemaMolmo2PointPart = components['schemas']['Molmo2PointPart'];
export type SchemaMultiModalModel = components['schemas']['MultiModalModel'];
export type SchemaMultiModalResponseModel = components['schemas']['MultiModalResponseModel'];
export type SchemaParameterDef = components['schemas']['ParameterDef'];
export type SchemaPromptTemplateResponse = components['schemas']['PromptTemplateResponse'];
export type SchemaPromptTemplateResponseList = components['schemas']['PromptTemplateResponseList'];
export type SchemaRating = components['schemas']['Rating'];
export type SchemaReorderModelConfigRequest = components['schemas']['ReorderModelConfigRequest'];
export type SchemaResponseAttributionDocument =
    components['schemas']['ResponseAttributionDocument'];
export type SchemaResponseAttributionSpan = components['schemas']['ResponseAttributionSpan'];
export type SchemaResponseModel = components['schemas']['ResponseModel'];
export type SchemaRole = components['schemas']['Role'];
export type SchemaRootCreateModelConfigRequest =
    components['schemas']['RootCreateModelConfigRequest'];
export type SchemaRootUpdateModelConfigRequest =
    components['schemas']['RootUpdateModelConfigRequest'];
export type SchemaSort = components['schemas']['Sort'];
export type SchemaSortDirection = components['schemas']['SortDirection'];
export type SchemaStreamEndChunk = components['schemas']['StreamEndChunk'];
export type SchemaStreamStartChunk = components['schemas']['StreamStartChunk'];
export type SchemaTextOnlyResponseModel = components['schemas']['TextOnlyResponseModel'];
export type SchemaThinkingChunk = components['schemas']['ThinkingChunk'];
export type SchemaThread = components['schemas']['Thread'];
export type SchemaToolCall = components['schemas']['ToolCall'];
export type SchemaToolCallChunk = components['schemas']['ToolCallChunk'];
export type SchemaToolDefinition = components['schemas']['ToolDefinition'];
export type SchemaToolSource = components['schemas']['ToolSource'];
export type SchemaTopLevelAttributionSpan = components['schemas']['TopLevelAttributionSpan'];
export type SchemaUpdateMultiModalModelConfigRequest =
    components['schemas']['UpdateMultiModalModelConfigRequest'];
export type SchemaUpdateTextOnlyModelConfigRequest =
    components['schemas']['UpdateTextOnlyModelConfigRequest'];
export type $defs = Record<string, never>;
type ReadonlyArray<T> = [Exclude<T, undefined>] extends [any[]]
    ? Readonly<Exclude<T, undefined>>
    : Readonly<Exclude<T, undefined>[]>;
export const availableInfiniGramIndexIdValues: ReadonlyArray<
    components['schemas']['AvailableInfiniGramIndexId']
> = [
    'olmoe-0125-1b-7b',
    'olmo-2-0325-32b',
    'olmo-2-1124-13b',
    'olmo-3-0625-32b-think',
    'olmo-3-0625-32b-instruct',
    'olmo-3-0625-7b-instruct',
    'olmo-3-0625-7b-think',
    'pileval-llama',
    'tulu-3-405b',
    'tulu-3-70b',
    'tulu-3-8b',
];
export const createMultiModalModelConfigRequestPromptTypeValues: ReadonlyArray<
    components['schemas']['CreateMultiModalModelConfigRequest']['promptType']
> = ['files_only', 'multi_modal'];
export const createTextOnlyModelConfigRequestPromptTypeValues: ReadonlyArray<
    components['schemas']['CreateTextOnlyModelConfigRequest']['promptType']
> = ['text_only'];
export const errorCodeValues: ReadonlyArray<components['schemas']['ErrorCode']> = ['toolCallError'];
export const errorSeverityValues: ReadonlyArray<components['schemas']['ErrorSeverity']> = [
    'error',
    'warning',
    'info',
];
export const fileRequiredToPromptOptionValues: ReadonlyArray<
    components['schemas']['FileRequiredToPromptOption']
> = ['first_message', 'all_messages', 'no_requirement'];
export const finishReasonValues: ReadonlyArray<components['schemas']['FinishReason']> = [
    'unclosed stream',
    'length',
    'stop',
    'aborted',
    'model overloaded',
    'bad connection',
    'value error',
    'tool error',
    'unknown',
];
export const modelPrompt_typeValues: ReadonlyArray<components['schemas']['Model']['prompt_type']> =
    ['text_only'];
export const modelAvailabilityValues: ReadonlyArray<components['schemas']['ModelAvailability']> = [
    'public',
    'internal',
    'prerelease',
];
export const modelHostValues: ReadonlyArray<components['schemas']['ModelHost']> = [
    'inferd',
    'modal',
    'beaker_queues',
    'cirrascale_backend',
    'cirrascale',
    'modal_openai',
    'test_backend',
    'ai2_model_hub',
];
export const modelTypeValues: ReadonlyArray<components['schemas']['ModelType']> = ['base', 'chat'];
export const multiModalModelPrompt_typeValues: ReadonlyArray<
    components['schemas']['MultiModalModel']['prompt_type']
> = ['files_only', 'multi_modal'];
export const multiModalResponseModelPromptTypeValues: ReadonlyArray<
    components['schemas']['MultiModalResponseModel']['promptType']
> = ['files_only', 'multi_modal'];
export const ratingValues: ReadonlyArray<components['schemas']['Rating']> = [-1, 0, 1];
export const roleValues: ReadonlyArray<components['schemas']['Role']> = [
    'user',
    'assistant',
    'system',
    'tool_call_result',
];
export const sortDirectionValues: ReadonlyArray<components['schemas']['SortDirection']> = [
    'ASC',
    'DESC',
];
export const textOnlyResponseModelPromptTypeValues: ReadonlyArray<
    components['schemas']['TextOnlyResponseModel']['promptType']
> = ['text_only'];
export const toolSourceValues: ReadonlyArray<components['schemas']['ToolSource']> = [
    'internal',
    'user_defined',
    'model_context_protocol',
];
export const updateMultiModalModelConfigRequestPromptTypeValues: ReadonlyArray<
    components['schemas']['UpdateMultiModalModelConfigRequest']['promptType']
> = ['files_only', 'multi_modal'];
export const updateTextOnlyModelConfigRequestPromptTypeValues: ReadonlyArray<
    components['schemas']['UpdateTextOnlyModelConfigRequest']['promptType']
> = ['text_only'];
export type operations = Record<string, never>;
