/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    readonly '/v3/attribution': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Get CorpusLink spans and documents from a prompt */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description A GetAttributionRequest */
            readonly requestBody: {
                readonly content: {
                    readonly 'application/json': components['schemas']['GetAttributionRequest'];
                };
            };
            readonly responses: {
                /** @description Empty Response */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/v3/whoami': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get info for the current user */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description A AuthenticatedClient */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly 'application/json': components['schemas']['AuthenticatedClient'];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/v4/message/stream': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Stream a prompt response */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description A CreateMessageRequestV4 */
            readonly requestBody: {
                readonly content: {
                    readonly 'application/json': components['schemas']['CreateMessageRequestV4'];
                };
            };
            readonly responses: {
                /** @description Empty Response */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/v4/models/': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get available models and their configuration */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Get the internal models for modification */
                    readonly admin?: boolean;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description A RootModelResponse */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly 'application/json': components['schemas']['RootModelResponse'];
                    };
                };
            };
        };
        /** Reorder models */
        readonly put: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description A ReorderModelConfigRequest */
            readonly requestBody: {
                readonly content: {
                    readonly 'application/json': components['schemas']['ReorderModelConfigRequest'];
                };
            };
            readonly responses: {
                /** @description Empty Response */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Add a new model */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description A RootCreateModelConfigRequest */
            readonly requestBody: {
                readonly content: {
                    readonly 'application/json': components['schemas']['RootCreateModelConfigRequest'];
                };
            };
            readonly responses: {
                /** @description A ResponseModel */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly 'application/json': components['schemas']['ResponseModel'];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/v4/models/{model_id}': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /** Update a model */
        readonly put: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly model_id: string;
                };
                readonly cookie?: never;
            };
            /** @description A RootUpdateModelConfigRequest */
            readonly requestBody: {
                readonly content: {
                    readonly 'application/json': components['schemas']['RootUpdateModelConfigRequest'];
                };
            };
            readonly responses: {
                /** @description A ResponseModel */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly 'application/json': components['schemas']['ResponseModel'];
                    };
                };
            };
        };
        readonly post?: never;
        /** Delete a model */
        readonly delete: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly model_id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Empty Response */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** AuthenticatedClient */
        readonly AuthenticatedClient: {
            /** Client */
            readonly client: string;
            /** Hasacceptedtermsandconditions */
            readonly hasAcceptedTermsAndConditions: boolean;
            /**
             * Id
             * @default null
             */
            readonly id?: string | null;
            /** Permissions */
            readonly permissions?: readonly string[];
        };
        /** CreateMessageRequestV4 */
        readonly CreateMessageRequestV4: {
            /**
             * Captchatoken
             * @default null
             */
            readonly captchaToken?: string | null;
            /** Content */
            readonly content: string;
            /** Host */
            readonly host: string;
            /**
             * Logprobs
             * @default null
             */
            readonly logprobs?: number | null;
            /**
             * Maxtokens
             * @default 2048
             */
            readonly maxTokens?: number;
            /** Model */
            readonly model: string;
            /**
             * N
             * @default 1
             */
            readonly n?: number;
            /**
             * Original
             * @default null
             */
            readonly original?: string | null;
            /**
             * Parent
             * @default null
             */
            readonly parent?: string | null;
            /**
             * Private
             * @default false
             */
            readonly private?: boolean;
            /** @default user */
            readonly role?: components['schemas']['Role'] | null;
            /**
             * Temperature
             * @default 0.7
             */
            readonly temperature?: number;
            /**
             * Template
             * @default null
             */
            readonly template?: string | null;
            /**
             * Topp
             * @default 1
             */
            readonly topP?: number;
        };
        /** CreateMultiModalModelConfigRequest */
        readonly CreateMultiModalModelConfigRequest: {
            /** Acceptedfiletypes */
            readonly acceptedFileTypes: readonly string[];
            /**
             * Allowfilesinfollowups
             * @default null
             */
            readonly allowFilesInFollowups?: boolean | null;
            /**
             * Availabletime
             * @default null
             */
            readonly availableTime?: string | null;
            /**
             * Defaultsystemprompt
             * @default null
             */
            readonly defaultSystemPrompt?: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            readonly deprecationTime?: string | null;
            /** Description */
            readonly description: string;
            /**
             * Familyid
             * @default null
             */
            readonly familyId?: string | null;
            /**
             * Familyname
             * @default null
             */
            readonly familyName?: string | null;
            readonly host: components['schemas']['ModelHost'];
            /** Id */
            readonly id: string;
            /**
             * Internal
             * @default true
             */
            readonly internal?: boolean;
            /**
             * Maxfilespermessage
             * @default null
             */
            readonly maxFilesPerMessage?: number | null;
            /**
             * Maxtotalfilesize
             * @default null
             */
            readonly maxTotalFileSize?: string | number | null;
            /** Modelidonhost */
            readonly modelIdOnHost: string;
            readonly modelType: components['schemas']['ModelType'];
            /** Name */
            readonly name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly promptType: 'multi_modal';
            /** @default null */
            readonly requireFileToPrompt?:
                | components['schemas']['FileRequiredToPromptOption']
                | null;
        };
        /** CreateTextOnlyModelConfigRequest */
        readonly CreateTextOnlyModelConfigRequest: {
            /**
             * Availabletime
             * @default null
             */
            readonly availableTime?: string | null;
            /**
             * Defaultsystemprompt
             * @default null
             */
            readonly defaultSystemPrompt?: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            readonly deprecationTime?: string | null;
            /** Description */
            readonly description: string;
            /**
             * Familyid
             * @default null
             */
            readonly familyId?: string | null;
            /**
             * Familyname
             * @default null
             */
            readonly familyName?: string | null;
            readonly host: components['schemas']['ModelHost'];
            /** Id */
            readonly id: string;
            /**
             * Internal
             * @default true
             */
            readonly internal?: boolean;
            /** Modelidonhost */
            readonly modelIdOnHost: string;
            readonly modelType: components['schemas']['ModelType'];
            /** Name */
            readonly name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly promptType: 'text_only';
        };
        /**
         * FileRequiredToPromptOption
         * @enum {string}
         */
        readonly FileRequiredToPromptOption: 'first_message' | 'all_messages' | 'no_requirement';
        /** GetAttributionRequest */
        readonly GetAttributionRequest: {
            /**
             * Maxdisplaycontextlength
             * @default 250
             */
            readonly maxDisplayContextLength?: number;
            /**
             * Maxdocuments
             * @default 10
             */
            readonly maxDocuments?: number;
            /** Modelid */
            readonly modelId: string;
            /** Modelresponse */
            readonly modelResponse: string;
            /** Prompt */
            readonly prompt: string;
        };
        /** Model */
        readonly Model: {
            /**
             * Accepts Files
             * @default false
             */
            readonly accepts_files?: boolean;
            /** Description */
            readonly description: string;
            /**
             * Family Id
             * @default null
             */
            readonly family_id?: string | null;
            /**
             * Family Name
             * @default null
             */
            readonly family_name?: string | null;
            readonly host: components['schemas']['ModelHost'];
            /** Id */
            readonly id: string;
            /** Internal */
            readonly internal: boolean;
            /** Is Deprecated */
            readonly is_deprecated: boolean;
            /** Is Visible */
            readonly is_visible: boolean;
            readonly model_type: components['schemas']['ModelType'];
            /** Name */
            readonly name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly prompt_type: 'text_only';
            /**
             * System Prompt
             * @default null
             */
            readonly system_prompt?: string | null;
        };
        /**
         * ModelAvailability
         * @enum {string}
         */
        readonly ModelAvailability: 'public' | 'internal' | 'prerelease';
        /**
         * ModelHost
         * @enum {string}
         */
        readonly ModelHost: 'inferd' | 'modal';
        /** ModelOrder */
        readonly ModelOrder: {
            /** Id */
            readonly id: string;
            /** Order */
            readonly order: number;
        };
        /**
         * ModelType
         * @enum {string}
         */
        readonly ModelType: 'base' | 'chat';
        /** MultiModalModel */
        readonly MultiModalModel: {
            /**
             * Accepted File Types
             * @description A list of file type specifiers: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#unique_file_type_specifiers
             */
            readonly accepted_file_types: readonly string[];
            /**
             * Accepts Files
             * @default false
             */
            readonly accepts_files?: boolean;
            /**
             * Allow Files In Followups
             * @description Defines if a user is allowed to send files with follow-up prompts. To require a file to prompt, use require_file_to_prompt
             * @default false
             */
            readonly allow_files_in_followups?: boolean;
            /** Description */
            readonly description: string;
            /**
             * Family Id
             * @default null
             */
            readonly family_id?: string | null;
            /**
             * Family Name
             * @default null
             */
            readonly family_name?: string | null;
            readonly host: components['schemas']['ModelHost'];
            /** Id */
            readonly id: string;
            /** Internal */
            readonly internal: boolean;
            /** Is Deprecated */
            readonly is_deprecated: boolean;
            /** Is Visible */
            readonly is_visible: boolean;
            /**
             * Max Files Per Message
             * @description The maximum number of files the user is allowed to send with a message
             * @default null
             */
            readonly max_files_per_message?: number | null;
            /**
             * Max Total File Size
             * @description The maximum total file size a user is allowed to send. Adds up the size of every file.
             * @default null
             */
            readonly max_total_file_size?: number | null;
            readonly model_type: components['schemas']['ModelType'];
            /** Name */
            readonly name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly prompt_type: 'multi_modal';
            /**
             * @description Defines if a user is required to send files with messages. Not intended to prevent users from sending files with follow-up messages.
             * @default no_requirement
             */
            readonly require_file_to_prompt?: components['schemas']['FileRequiredToPromptOption'];
            /**
             * System Prompt
             * @default null
             */
            readonly system_prompt?: string | null;
        };
        /** MultiModalResponseModel */
        readonly MultiModalResponseModel: {
            /** Acceptedfiletypes */
            readonly acceptedFileTypes: readonly string[];
            /**
             * Allowfilesinfollowups
             * @default null
             */
            readonly allowFilesInFollowups?: boolean | null;
            readonly availability: components['schemas']['ModelAvailability'];
            /**
             * Availabletime
             * @default null
             */
            readonly availableTime?: string | null;
            /**
             * Createdtime
             * Format: date-time
             */
            readonly createdTime: string;
            /**
             * Defaultsystemprompt
             * @default null
             */
            readonly defaultSystemPrompt?: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            readonly deprecationTime?: string | null;
            /** Description */
            readonly description: string;
            /**
             * Familyid
             * @default null
             */
            readonly familyId?: string | null;
            /**
             * Familyname
             * @default null
             */
            readonly familyName?: string | null;
            readonly host: components['schemas']['ModelHost'];
            /** Id */
            readonly id: string;
            /** Internal */
            readonly internal: boolean;
            /**
             * Maxfilespermessage
             * @default null
             */
            readonly maxFilesPerMessage?: number | null;
            /**
             * Maxtotalfilesize
             * @default null
             */
            readonly maxTotalFileSize?: number | null;
            /** Modelidonhost */
            readonly modelIdOnHost: string;
            readonly modelType: components['schemas']['ModelType'];
            /** Name */
            readonly name: string;
            /** Order */
            readonly order: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly promptType: 'multi_modal';
            /** @default null */
            readonly requireFileToPrompt?:
                | components['schemas']['FileRequiredToPromptOption']
                | null;
            /**
             * Updatedtime
             * Format: date-time
             */
            readonly updatedTime: string;
        };
        /** ReorderModelConfigRequest */
        readonly ReorderModelConfigRequest: {
            /** Orderedmodels */
            readonly orderedModels: readonly components['schemas']['ModelOrder'][];
        };
        /** ResponseModel */
        readonly ResponseModel:
            | components['schemas']['TextOnlyResponseModel']
            | components['schemas']['MultiModalResponseModel'];
        /**
         * Role
         * @enum {string}
         */
        readonly Role: 'user' | 'assistant' | 'system';
        /** RootCreateModelConfigRequest */
        readonly RootCreateModelConfigRequest:
            | components['schemas']['CreateTextOnlyModelConfigRequest']
            | components['schemas']['CreateMultiModalModelConfigRequest'];
        /** RootModelResponse */
        readonly RootModelResponse:
            | readonly (components['schemas']['Model'] | components['schemas']['MultiModalModel'])[]
            | readonly components['schemas']['ResponseModel'][];
        /** RootUpdateModelConfigRequest */
        readonly RootUpdateModelConfigRequest:
            | components['schemas']['UpdateTextOnlyModelConfigRequest']
            | components['schemas']['UpdateMultiModalModelConfigRequest'];
        /** TextOnlyResponseModel */
        readonly TextOnlyResponseModel: {
            readonly availability: components['schemas']['ModelAvailability'];
            /**
             * Availabletime
             * @default null
             */
            readonly availableTime?: string | null;
            /**
             * Createdtime
             * Format: date-time
             */
            readonly createdTime: string;
            /**
             * Defaultsystemprompt
             * @default null
             */
            readonly defaultSystemPrompt?: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            readonly deprecationTime?: string | null;
            /** Description */
            readonly description: string;
            /**
             * Familyid
             * @default null
             */
            readonly familyId?: string | null;
            /**
             * Familyname
             * @default null
             */
            readonly familyName?: string | null;
            readonly host: components['schemas']['ModelHost'];
            /** Id */
            readonly id: string;
            /** Internal */
            readonly internal: boolean;
            /** Modelidonhost */
            readonly modelIdOnHost: string;
            readonly modelType: components['schemas']['ModelType'];
            /** Name */
            readonly name: string;
            /** Order */
            readonly order: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly promptType: 'text_only';
            /**
             * Updatedtime
             * Format: date-time
             */
            readonly updatedTime: string;
        };
        /** UpdateMultiModalModelConfigRequest */
        readonly UpdateMultiModalModelConfigRequest: {
            /** Acceptedfiletypes */
            readonly acceptedFileTypes: readonly string[];
            /**
             * Allowfilesinfollowups
             * @default null
             */
            readonly allowFilesInFollowups?: boolean | null;
            /**
             * Availabletime
             * @default null
             */
            readonly availableTime?: string | null;
            /**
             * Defaultsystemprompt
             * @default null
             */
            readonly defaultSystemPrompt?: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            readonly deprecationTime?: string | null;
            /** Description */
            readonly description: string;
            /**
             * Familyid
             * @default null
             */
            readonly familyId?: string | null;
            /**
             * Familyname
             * @default null
             */
            readonly familyName?: string | null;
            readonly host: components['schemas']['ModelHost'];
            /**
             * Internal
             * @default true
             */
            readonly internal?: boolean;
            /**
             * Maxfilespermessage
             * @default null
             */
            readonly maxFilesPerMessage?: number | null;
            /**
             * Maxtotalfilesize
             * @default null
             */
            readonly maxTotalFileSize?: string | number | null;
            /** Modelidonhost */
            readonly modelIdOnHost: string;
            readonly modelType: components['schemas']['ModelType'];
            /** Name */
            readonly name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly promptType: 'multi_modal';
            /** @default null */
            readonly requireFileToPrompt?:
                | components['schemas']['FileRequiredToPromptOption']
                | null;
        };
        /** UpdateTextOnlyModelConfigRequest */
        readonly UpdateTextOnlyModelConfigRequest: {
            /**
             * Availabletime
             * @default null
             */
            readonly availableTime?: string | null;
            /**
             * Defaultsystemprompt
             * @default null
             */
            readonly defaultSystemPrompt?: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            readonly deprecationTime?: string | null;
            /** Description */
            readonly description: string;
            /**
             * Familyid
             * @default null
             */
            readonly familyId?: string | null;
            /**
             * Familyname
             * @default null
             */
            readonly familyName?: string | null;
            readonly host: components['schemas']['ModelHost'];
            /**
             * Internal
             * @default true
             */
            readonly internal?: boolean;
            /** Modelidonhost */
            readonly modelIdOnHost: string;
            readonly modelType: components['schemas']['ModelType'];
            /** Name */
            readonly name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly promptType: 'text_only';
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type SchemaAuthenticatedClient = components['schemas']['AuthenticatedClient'];
export type SchemaCreateMessageRequestV4 = components['schemas']['CreateMessageRequestV4'];
export type SchemaCreateMultiModalModelConfigRequest =
    components['schemas']['CreateMultiModalModelConfigRequest'];
export type SchemaCreateTextOnlyModelConfigRequest =
    components['schemas']['CreateTextOnlyModelConfigRequest'];
export type SchemaFileRequiredToPromptOption = components['schemas']['FileRequiredToPromptOption'];
export type SchemaGetAttributionRequest = components['schemas']['GetAttributionRequest'];
export type SchemaModel = components['schemas']['Model'];
export type SchemaModelAvailability = components['schemas']['ModelAvailability'];
export type SchemaModelHost = components['schemas']['ModelHost'];
export type SchemaModelOrder = components['schemas']['ModelOrder'];
export type SchemaModelType = components['schemas']['ModelType'];
export type SchemaMultiModalModel = components['schemas']['MultiModalModel'];
export type SchemaMultiModalResponseModel = components['schemas']['MultiModalResponseModel'];
export type SchemaReorderModelConfigRequest = components['schemas']['ReorderModelConfigRequest'];
export type SchemaResponseModel = components['schemas']['ResponseModel'];
export type SchemaRole = components['schemas']['Role'];
export type SchemaRootCreateModelConfigRequest =
    components['schemas']['RootCreateModelConfigRequest'];
export type SchemaRootModelResponse = components['schemas']['RootModelResponse'];
export type SchemaRootUpdateModelConfigRequest =
    components['schemas']['RootUpdateModelConfigRequest'];
export type SchemaTextOnlyResponseModel = components['schemas']['TextOnlyResponseModel'];
export type SchemaUpdateMultiModalModelConfigRequest =
    components['schemas']['UpdateMultiModalModelConfigRequest'];
export type SchemaUpdateTextOnlyModelConfigRequest =
    components['schemas']['UpdateTextOnlyModelConfigRequest'];
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
