import createFetchClient, { type Middleware } from 'openapi-fetch';
import createClient from 'openapi-react-query';

import { auth0Client } from '@/api/auth/auth0Client';
import { ANONYMOUS_USER_ID_KEY } from '@/api/ClientBase';

import type { paths } from './playgroundApiSchema'; // generated by openapi-typescript

const authMiddleware: Middleware = {
    async onRequest({ request }) {
        const token = await auth0Client.getToken();
        if (token) {
            request.headers.set('Authorization', `Bearer ${token}`);
        } else {
            const anonymousUserId = window.localStorage.getItem(ANONYMOUS_USER_ID_KEY);

            if (anonymousUserId) {
                request.headers.set('X-Anonymous-User-ID', anonymousUserId);
            }
        }
    },
};

export const playgroundApiClient = createFetchClient<paths>({
    baseUrl: process.env.VITE_API_URL,
    // This fixes an issue with openapi-fetch not cooperating with MSW
    // https://www.martinrichards.me/post/an_idiots_guide_to_msw/
    fetch: (req) => fetch(req),
});
playgroundApiClient.use(authMiddleware);

export const playgroundApiQueryClient = createClient(playgroundApiClient);
