/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    readonly '/v3/attribution': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Get CorpusLink spans and documents from a prompt */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description A GetAttributionRequest */
            readonly requestBody: {
                readonly content: {
                    readonly 'application/json': components['schemas']['GetAttributionRequest'];
                };
            };
            readonly responses: {
                /** @description Empty Response */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/v3/whoami': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get info for the current user */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description A AuthenticatedClient */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly 'application/json': components['schemas']['AuthenticatedClient'];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/v4/admin/models/': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get full details of a model */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description A AdminModelResponse */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly 'application/json': components['schemas']['AdminModelResponse'];
                    };
                };
            };
        };
        /** Reorder models */
        readonly put: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description A ReorderModelConfigRequest */
            readonly requestBody: {
                readonly content: {
                    readonly 'application/json': components['schemas']['ReorderModelConfigRequest'];
                };
            };
            readonly responses: {
                /** @description Empty Response */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Add a new model */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description A RootCreateModelConfigRequest */
            readonly requestBody: {
                readonly content: {
                    readonly 'application/json': components['schemas']['RootCreateModelConfigRequest'];
                };
            };
            readonly responses: {
                /** @description A ResponseModel */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly 'application/json': components['schemas']['ResponseModel'];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/v4/admin/models/{model_id}': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        /** Update a model */
        readonly put: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly model_id: string;
                };
                readonly cookie?: never;
            };
            /** @description A RootUpdateModelConfigRequest */
            readonly requestBody: {
                readonly content: {
                    readonly 'application/json': components['schemas']['RootUpdateModelConfigRequest'];
                };
            };
            readonly responses: {
                /** @description A ResponseModel */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly 'application/json': components['schemas']['ResponseModel'];
                    };
                };
            };
        };
        readonly post?: never;
        /** Delete a model */
        readonly delete: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly model_id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Empty Response */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/v4/message/stream': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Stream a prompt response */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description A CreateMessageRequest */
            readonly requestBody: {
                readonly content: {
                    readonly 'application/json': components['schemas']['CreateMessageRequest'];
                };
            };
            readonly responses: {
                /** @description Empty Response */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/v4/models/': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get available models */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description A ModelResponse */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly 'application/json': components['schemas']['ModelResponse'];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/v4/threads/': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get messages */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description A GetThreadsRequest */
            readonly requestBody: {
                readonly content: {
                    readonly 'application/json': components['schemas']['GetThreadsRequest'];
                };
            };
            readonly responses: {
                /** @description A GetThreadsResponse */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly 'application/json': components['schemas']['GetThreadsResponse'];
                    };
                };
            };
        };
        readonly put?: never;
        /** Stream a prompt response */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description A CreateMessageRequest */
            readonly requestBody: {
                readonly content: {
                    readonly 'application/json': components['schemas']['CreateMessageRequest'];
                };
            };
            readonly responses: {
                /** @description Empty Response */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/v4/threads/{thread_id}': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get message */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly thread_id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description A Thread */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly 'application/json': components['schemas']['Thread'];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/v4/transcribe/': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Transcribe audio */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            /** @description A GetTranscriptionRequest */
            readonly requestBody: {
                readonly content: {
                    readonly 'multipart/form-data': components['schemas']['GetTranscriptionRequest'];
                };
            };
            readonly responses: {
                /** @description A GetTranscriptionResponse */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly 'application/json': components['schemas']['GetTranscriptionResponse'];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** AdminModelResponse */
        readonly AdminModelResponse: readonly components['schemas']['ResponseModel'][];
        /** AuthenticatedClient */
        readonly AuthenticatedClient: {
            /** Client */
            readonly client: string;
            /** Hasaccepteddatacollection */
            readonly hasAcceptedDataCollection: boolean;
            /** Hasacceptedtermsandconditions */
            readonly hasAcceptedTermsAndConditions: boolean;
            /**
             * Id
             * @default null
             */
            readonly id?: string | null;
            /** Permissions */
            readonly permissions?: readonly string[];
        };
        /** CreateMessageRequest */
        readonly CreateMessageRequest: {
            /**
             * Captchatoken
             * @default null
             */
            readonly captchaToken?: string | null;
            /** Content */
            readonly content: string;
            /** Host */
            readonly host: string;
            /**
             * Logprobs
             * @default null
             */
            readonly logprobs?: number | null;
            /**
             * Maxtokens
             * @default 2048
             */
            readonly maxTokens?: number;
            /** Model */
            readonly model: string;
            /**
             * N
             * @default 1
             */
            readonly n?: number;
            /**
             * Original
             * @default null
             */
            readonly original?: string | null;
            /**
             * Parent
             * @default null
             */
            readonly parent?: string | null;
            /**
             * Private
             * @default false
             */
            readonly private?: boolean;
            /** @default user */
            readonly role?: components['schemas']['Role'] | null;
            /**
             * Temperature
             * @default 0.7
             */
            readonly temperature?: number;
            /**
             * Template
             * @default null
             */
            readonly template?: string | null;
            /**
             * Topp
             * @default 1
             */
            readonly topP?: number;
        };
        /** CreateMultiModalModelConfigRequest */
        readonly CreateMultiModalModelConfigRequest: {
            /** Acceptedfiletypes */
            readonly acceptedFileTypes: readonly string[];
            /**
             * Allowfilesinfollowups
             * @default null
             */
            readonly allowFilesInFollowups?: boolean | null;
            /**
             * Availabletime
             * @default null
             */
            readonly availableTime?: string | null;
            /**
             * Cancalltools
             * @default false
             */
            readonly canCallTools?: boolean;
            /**
             * Defaultsystemprompt
             * @default null
             */
            readonly defaultSystemPrompt?: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            readonly deprecationTime?: string | null;
            /** Description */
            readonly description: string;
            /**
             * Familyid
             * @default null
             */
            readonly familyId?: string | null;
            /**
             * Familyname
             * @default null
             */
            readonly familyName?: string | null;
            readonly host: components['schemas']['ModelHost'];
            /** Id */
            readonly id: string;
            /**
             * Internal
             * @default true
             */
            readonly internal?: boolean;
            /**
             * Maxfilespermessage
             * @default null
             */
            readonly maxFilesPerMessage?: number | null;
            /**
             * Maxtotalfilesize
             * @default null
             */
            readonly maxTotalFileSize?: string | number | null;
            /** Modelidonhost */
            readonly modelIdOnHost: string;
            readonly modelType: components['schemas']['ModelType'];
            /** Name */
            readonly name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly promptType: 'files_only' | 'multi_modal';
            /** @default null */
            readonly requireFileToPrompt?:
                | components['schemas']['FileRequiredToPromptOption']
                | null;
        };
        /** CreateTextOnlyModelConfigRequest */
        readonly CreateTextOnlyModelConfigRequest: {
            /**
             * Availabletime
             * @default null
             */
            readonly availableTime?: string | null;
            /**
             * Cancalltools
             * @default false
             */
            readonly canCallTools?: boolean;
            /**
             * Defaultsystemprompt
             * @default null
             */
            readonly defaultSystemPrompt?: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            readonly deprecationTime?: string | null;
            /** Description */
            readonly description: string;
            /**
             * Familyid
             * @default null
             */
            readonly familyId?: string | null;
            /**
             * Familyname
             * @default null
             */
            readonly familyName?: string | null;
            readonly host: components['schemas']['ModelHost'];
            /** Id */
            readonly id: string;
            /**
             * Internal
             * @default true
             */
            readonly internal?: boolean;
            /** Modelidonhost */
            readonly modelIdOnHost: string;
            readonly modelType: components['schemas']['ModelType'];
            /** Name */
            readonly name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly promptType: 'text_only';
        };
        /**
         * FileRequiredToPromptOption
         * @enum {string}
         */
        readonly FileRequiredToPromptOption: 'first_message' | 'all_messages' | 'no_requirement';
        /**
         * FinishReason
         * @enum {string}
         */
        readonly FinishReason:
            | 'unclosed stream'
            | 'length'
            | 'stop'
            | 'aborted'
            | 'model overloaded'
            | 'bad connection'
            | 'value error'
            | 'unknown';
        /** FlatMessage */
        readonly FlatMessage: {
            /**
             * Children
             * @default null
             */
            readonly children?: readonly string[] | null;
            /**
             * Completion
             * @default null
             */
            readonly completion?: string | null;
            /** Content */
            readonly content: string;
            /**
             * Created
             * Format: date-time
             */
            readonly created: string;
            /** Creator */
            readonly creator: string;
            /**
             * Deleted
             * @default null
             */
            readonly deleted?: string | null;
            /**
             * Expirationtime
             * @default null
             */
            readonly expirationTime?: string | null;
            /**
             * Fileurls
             * @default null
             */
            readonly fileUrls?: readonly string[] | null;
            /**
             * Final
             * @default false
             */
            readonly final?: boolean;
            /** @default null */
            readonly finishReason?: components['schemas']['FinishReason'] | null;
            /**
             * Harmful
             * @default null
             */
            readonly harmful?: boolean | null;
            /** Id */
            readonly id: string;
            /** Islimitreached */
            readonly isLimitReached: boolean;
            /** Isolderthan30Days */
            readonly isOlderThan30Days: boolean;
            /** Labels */
            readonly labels?: readonly components['schemas']['LabelResponse'][];
            /** Modelhost */
            readonly modelHost: string;
            /** Modelid */
            readonly modelId: string;
            /** @default null */
            readonly modelType?: components['schemas']['ModelType'] | null;
            readonly opts: components['schemas']['InferenceOptionsResponse'];
            /**
             * Original
             * @default null
             */
            readonly original?: string | null;
            /**
             * Parent
             * @default null
             */
            readonly parent?: string | null;
            /**
             * Private
             * @default false
             */
            readonly private?: boolean;
            readonly role: components['schemas']['Role'];
            /** Root */
            readonly root: string;
            /** Snippet */
            readonly snippet: string;
            /**
             * Template
             * @default null
             */
            readonly template?: string | null;
            /**
             * Thinking
             * @default null
             */
            readonly thinking?: string | null;
            /**
             * Toolcalls
             * @default null
             */
            readonly toolCalls?: readonly components['schemas']['ToolCall'][] | null;
        };
        /** GetAttributionRequest */
        readonly GetAttributionRequest: {
            /**
             * Maxdisplaycontextlength
             * @default 250
             */
            readonly maxDisplayContextLength?: number;
            /**
             * Maxdocuments
             * @default 10
             */
            readonly maxDocuments?: number;
            /** Modelid */
            readonly modelId: string;
            /** Modelresponse */
            readonly modelResponse: string;
            /** Prompt */
            readonly prompt: string;
        };
        /** GetThreadsRequest */
        readonly GetThreadsRequest: {
            /**
             * Creator
             * @default null
             */
            readonly creator?: string | null;
            /**
             * Deleted
             * @default false
             */
            readonly deleted?: boolean;
            /**
             * Limit
             * @default 10
             */
            readonly limit?: number;
            /**
             * Offset
             * @default 0
             */
            readonly offset?: number | null;
            /** @default DESC */
            readonly order?: components['schemas']['SortDirection'];
            /**
             * Sort
             * @default null
             */
            readonly sort?: string | null;
        };
        /** GetThreadsResponse */
        readonly GetThreadsResponse: {
            readonly meta: components['schemas']['ListMeta'];
            /** Threads */
            readonly threads: readonly components['schemas']['Thread'][];
        };
        /** GetTranscriptionRequest */
        readonly GetTranscriptionRequest: {
            /**
             * Audio
             * Format: binary
             */
            readonly audio: string;
        };
        /** GetTranscriptionResponse */
        readonly GetTranscriptionResponse: {
            /** Text */
            readonly text: string;
        };
        /** InferenceOptionsResponse */
        readonly InferenceOptionsResponse: {
            /**
             * Logprobs
             * @default null
             */
            readonly logprobs?: number | null;
            /**
             * Maxtokens
             * @default 2048
             */
            readonly maxTokens?: number;
            /**
             * N
             * @default 1
             */
            readonly n?: number;
            /**
             * Stop
             * @default null
             */
            readonly stop?: readonly string[] | null;
            /**
             * Temperature
             * @default 0.7
             */
            readonly temperature?: number;
            /**
             * Topp
             * @default 1
             */
            readonly topP?: number;
        };
        /** LabelResponse */
        readonly LabelResponse: {
            /**
             * Comment
             * @default null
             */
            readonly comment?: string | null;
            /**
             * Created
             * Format: date-time
             */
            readonly created: string;
            /** Creator */
            readonly creator: string;
            /**
             * Deleted
             * @default null
             */
            readonly deleted?: string | null;
            /** Id */
            readonly id: string;
            /** Message */
            readonly message: string;
            readonly rating: components['schemas']['Rating'];
        };
        /** ListMeta */
        readonly ListMeta: {
            /**
             * Limit
             * @default null
             */
            readonly limit?: number | null;
            /**
             * Offset
             * @default null
             */
            readonly offset?: number | null;
            /** @default null */
            readonly sort?: components['schemas']['Sort'] | null;
            /** Total */
            readonly total: number;
        };
        /** Model */
        readonly Model: {
            /**
             * Accepts Files
             * @default false
             */
            readonly accepts_files?: boolean;
            /** Description */
            readonly description: string;
            /**
             * Family Id
             * @default null
             */
            readonly family_id?: string | null;
            /**
             * Family Name
             * @default null
             */
            readonly family_name?: string | null;
            readonly host: components['schemas']['ModelHost'];
            /** Id */
            readonly id: string;
            /** Internal */
            readonly internal: boolean;
            /** Is Deprecated */
            readonly is_deprecated: boolean;
            /** Is Visible */
            readonly is_visible: boolean;
            readonly model_type: components['schemas']['ModelType'];
            /** Name */
            readonly name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly prompt_type: 'text_only';
            /**
             * System Prompt
             * @default null
             */
            readonly system_prompt?: string | null;
        };
        /**
         * ModelAvailability
         * @enum {string}
         */
        readonly ModelAvailability: 'public' | 'internal' | 'prerelease';
        /**
         * ModelHost
         * @enum {string}
         */
        readonly ModelHost:
            | 'inferd'
            | 'modal'
            | 'beaker_queues'
            | 'cirrascale_backend'
            | 'cirrascale'
            | 'modal_openai'
            | 'test_backend';
        /** ModelOrder */
        readonly ModelOrder: {
            /** Id */
            readonly id: string;
            /** Order */
            readonly order: number;
        };
        /** ModelResponse */
        readonly ModelResponse: readonly (
            | components['schemas']['Model']
            | components['schemas']['MultiModalModel']
        )[];
        /** ModelResponseChunk */
        readonly ModelResponseChunk: {
            /** Content */
            readonly content: string;
            /** Message */
            readonly message: string;
            /**
             * Type
             * @constant
             */
            readonly type: 'modelResponse';
        };
        /**
         * ModelType
         * @enum {string}
         */
        readonly ModelType: 'base' | 'chat';
        /** MultiModalModel */
        readonly MultiModalModel: {
            /**
             * Accepted File Types
             * @description A list of file type specifiers: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#unique_file_type_specifiers
             */
            readonly accepted_file_types: readonly string[];
            /**
             * Accepts Files
             * @default false
             */
            readonly accepts_files?: boolean;
            /**
             * Allow Files In Followups
             * @description Defines if a user is allowed to send files with follow-up prompts. To require a file to prompt, use require_file_to_prompt
             * @default false
             */
            readonly allow_files_in_followups?: boolean;
            /** Description */
            readonly description: string;
            /**
             * Family Id
             * @default null
             */
            readonly family_id?: string | null;
            /**
             * Family Name
             * @default null
             */
            readonly family_name?: string | null;
            readonly host: components['schemas']['ModelHost'];
            /** Id */
            readonly id: string;
            /** Internal */
            readonly internal: boolean;
            /** Is Deprecated */
            readonly is_deprecated: boolean;
            /** Is Visible */
            readonly is_visible: boolean;
            /**
             * Max Files Per Message
             * @description The maximum number of files the user is allowed to send with a message
             * @default null
             */
            readonly max_files_per_message?: number | null;
            /**
             * Max Total File Size
             * @description The maximum total file size a user is allowed to send. Adds up the size of every file.
             * @default null
             */
            readonly max_total_file_size?: number | null;
            readonly model_type: components['schemas']['ModelType'];
            /** Name */
            readonly name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly prompt_type: 'files_only' | 'multi_modal';
            /**
             * @description Defines if a user is required to send files with messages. Not intended to prevent users from sending files with follow-up messages.
             * @default no_requirement
             */
            readonly require_file_to_prompt?: components['schemas']['FileRequiredToPromptOption'];
            /**
             * System Prompt
             * @default null
             */
            readonly system_prompt?: string | null;
        };
        /** MultiModalResponseModel */
        readonly MultiModalResponseModel: {
            /** Acceptedfiletypes */
            readonly acceptedFileTypes: readonly string[];
            /**
             * Allowfilesinfollowups
             * @default null
             */
            readonly allowFilesInFollowups?: boolean | null;
            readonly availability: components['schemas']['ModelAvailability'];
            /**
             * Availabletime
             * @default null
             */
            readonly availableTime?: string | null;
            /** Cancalltools */
            readonly canCallTools: boolean;
            /**
             * Createdtime
             * Format: date-time
             */
            readonly createdTime: string;
            /**
             * Defaultsystemprompt
             * @default null
             */
            readonly defaultSystemPrompt?: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            readonly deprecationTime?: string | null;
            /** Description */
            readonly description: string;
            /**
             * Familyid
             * @default null
             */
            readonly familyId?: string | null;
            /**
             * Familyname
             * @default null
             */
            readonly familyName?: string | null;
            readonly host: components['schemas']['ModelHost'];
            /** Id */
            readonly id: string;
            /** Internal */
            readonly internal: boolean;
            /**
             * Maxfilespermessage
             * @default null
             */
            readonly maxFilesPerMessage?: number | null;
            /**
             * Maxtotalfilesize
             * @default null
             */
            readonly maxTotalFileSize?: number | null;
            /** Modelidonhost */
            readonly modelIdOnHost: string;
            readonly modelType: components['schemas']['ModelType'];
            /** Name */
            readonly name: string;
            /** Order */
            readonly order: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly promptType: 'files_only' | 'multi_modal';
            /** @default null */
            readonly requireFileToPrompt?:
                | components['schemas']['FileRequiredToPromptOption']
                | null;
            /**
             * Updatedtime
             * Format: date-time
             */
            readonly updatedTime: string;
        };
        /**
         * Rating
         * @enum {integer}
         */
        readonly Rating: -1 | 0 | 1;
        /** ReorderModelConfigRequest */
        readonly ReorderModelConfigRequest: {
            /** Orderedmodels */
            readonly orderedModels: readonly components['schemas']['ModelOrder'][];
        };
        /** ResponseModel */
        readonly ResponseModel:
            | components['schemas']['TextOnlyResponseModel']
            | components['schemas']['MultiModalResponseModel'];
        /**
         * Role
         * @enum {string}
         */
        readonly Role: 'user' | 'assistant' | 'system' | 'tool_call_result';
        /** RootCreateModelConfigRequest */
        readonly RootCreateModelConfigRequest:
            | components['schemas']['CreateTextOnlyModelConfigRequest']
            | components['schemas']['CreateMultiModalModelConfigRequest'];
        /** RootUpdateModelConfigRequest */
        readonly RootUpdateModelConfigRequest:
            | components['schemas']['UpdateTextOnlyModelConfigRequest']
            | components['schemas']['UpdateMultiModalModelConfigRequest'];
        /** Sort */
        readonly Sort: {
            /** @default DESC */
            readonly direction?: components['schemas']['SortDirection'];
            /** Field */
            readonly field: string;
        };
        /**
         * SortDirection
         * @enum {string}
         */
        readonly SortDirection: 'ASC' | 'DESC';
        /** StreamEndChunk */
        readonly StreamEndChunk: {
            /** Message */
            readonly message: string;
            /**
             * Type
             * @default end
             * @constant
             */
            readonly type?: 'end';
        };
        /** StreamStartChunk */
        readonly StreamStartChunk: {
            /** Message */
            readonly message: string;
            /**
             * Type
             * @default start
             * @constant
             */
            readonly type?: 'start';
        };
        /** TextOnlyResponseModel */
        readonly TextOnlyResponseModel: {
            readonly availability: components['schemas']['ModelAvailability'];
            /**
             * Availabletime
             * @default null
             */
            readonly availableTime?: string | null;
            /** Cancalltools */
            readonly canCallTools: boolean;
            /**
             * Createdtime
             * Format: date-time
             */
            readonly createdTime: string;
            /**
             * Defaultsystemprompt
             * @default null
             */
            readonly defaultSystemPrompt?: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            readonly deprecationTime?: string | null;
            /** Description */
            readonly description: string;
            /**
             * Familyid
             * @default null
             */
            readonly familyId?: string | null;
            /**
             * Familyname
             * @default null
             */
            readonly familyName?: string | null;
            readonly host: components['schemas']['ModelHost'];
            /** Id */
            readonly id: string;
            /** Internal */
            readonly internal: boolean;
            /** Modelidonhost */
            readonly modelIdOnHost: string;
            readonly modelType: components['schemas']['ModelType'];
            /** Name */
            readonly name: string;
            /** Order */
            readonly order: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly promptType: 'text_only';
            /**
             * Updatedtime
             * Format: date-time
             */
            readonly updatedTime: string;
        };
        /** ThinkingChunk */
        readonly ThinkingChunk: {
            /** Content */
            readonly content: string;
            /**
             * Id
             * @default null
             */
            readonly id?: string | null;
            /** Message */
            readonly message: string;
            /**
             * Type
             * @constant
             */
            readonly type: 'thinking';
        };
        /** Thread */
        readonly Thread: {
            /** Id */
            readonly id: string;
            /** Messages */
            readonly messages: readonly components['schemas']['FlatMessage'][];
        };
        /** ToolCall */
        readonly ToolCall: {
            /**
             * Args
             * @default null
             */
            readonly args?:
                | string
                | {
                      readonly [key: string]: unknown;
                  }
                | null;
            /** Toolcallid */
            readonly toolCallId: string;
            /** Toolname */
            readonly toolName: string;
        };
        /** ToolCallChunk */
        readonly ToolCallChunk: {
            /**
             * Args
             * @default null
             */
            readonly args?:
                | string
                | {
                      readonly [key: string]: unknown;
                  }
                | null;
            /** Message */
            readonly message: string;
            /** Toolcallid */
            readonly toolCallId: string;
            /** Toolname */
            readonly toolName: string;
            /**
             * Type
             * @constant
             */
            readonly type: 'toolCall';
        };
        /** UpdateMultiModalModelConfigRequest */
        readonly UpdateMultiModalModelConfigRequest: {
            /** Acceptedfiletypes */
            readonly acceptedFileTypes: readonly string[];
            /**
             * Allowfilesinfollowups
             * @default null
             */
            readonly allowFilesInFollowups?: boolean | null;
            /**
             * Availabletime
             * @default null
             */
            readonly availableTime?: string | null;
            /**
             * Cancalltools
             * @default false
             */
            readonly canCallTools?: boolean;
            /**
             * Defaultsystemprompt
             * @default null
             */
            readonly defaultSystemPrompt?: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            readonly deprecationTime?: string | null;
            /** Description */
            readonly description: string;
            /**
             * Familyid
             * @default null
             */
            readonly familyId?: string | null;
            /**
             * Familyname
             * @default null
             */
            readonly familyName?: string | null;
            readonly host: components['schemas']['ModelHost'];
            /**
             * Internal
             * @default true
             */
            readonly internal?: boolean;
            /**
             * Maxfilespermessage
             * @default null
             */
            readonly maxFilesPerMessage?: number | null;
            /**
             * Maxtotalfilesize
             * @default null
             */
            readonly maxTotalFileSize?: string | number | null;
            /** Modelidonhost */
            readonly modelIdOnHost: string;
            readonly modelType: components['schemas']['ModelType'];
            /** Name */
            readonly name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly promptType: 'files_only' | 'multi_modal';
            /** @default null */
            readonly requireFileToPrompt?:
                | components['schemas']['FileRequiredToPromptOption']
                | null;
        };
        /** UpdateTextOnlyModelConfigRequest */
        readonly UpdateTextOnlyModelConfigRequest: {
            /**
             * Availabletime
             * @default null
             */
            readonly availableTime?: string | null;
            /**
             * Cancalltools
             * @default false
             */
            readonly canCallTools?: boolean;
            /**
             * Defaultsystemprompt
             * @default null
             */
            readonly defaultSystemPrompt?: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            readonly deprecationTime?: string | null;
            /** Description */
            readonly description: string;
            /**
             * Familyid
             * @default null
             */
            readonly familyId?: string | null;
            /**
             * Familyname
             * @default null
             */
            readonly familyName?: string | null;
            readonly host: components['schemas']['ModelHost'];
            /**
             * Internal
             * @default true
             */
            readonly internal?: boolean;
            /** Modelidonhost */
            readonly modelIdOnHost: string;
            readonly modelType: components['schemas']['ModelType'];
            /** Name */
            readonly name: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly promptType: 'text_only';
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type SchemaAdminModelResponse = components['schemas']['AdminModelResponse'];
export type SchemaAuthenticatedClient = components['schemas']['AuthenticatedClient'];
export type SchemaCreateMessageRequest = components['schemas']['CreateMessageRequest'];
export type SchemaCreateMultiModalModelConfigRequest =
    components['schemas']['CreateMultiModalModelConfigRequest'];
export type SchemaCreateTextOnlyModelConfigRequest =
    components['schemas']['CreateTextOnlyModelConfigRequest'];
export type SchemaFileRequiredToPromptOption = components['schemas']['FileRequiredToPromptOption'];
export type SchemaFinishReason = components['schemas']['FinishReason'];
export type SchemaFlatMessage = components['schemas']['FlatMessage'];
export type SchemaGetAttributionRequest = components['schemas']['GetAttributionRequest'];
export type SchemaGetThreadsRequest = components['schemas']['GetThreadsRequest'];
export type SchemaGetThreadsResponse = components['schemas']['GetThreadsResponse'];
export type SchemaGetTranscriptionRequest = components['schemas']['GetTranscriptionRequest'];
export type SchemaGetTranscriptionResponse = components['schemas']['GetTranscriptionResponse'];
export type SchemaInferenceOptionsResponse = components['schemas']['InferenceOptionsResponse'];
export type SchemaLabelResponse = components['schemas']['LabelResponse'];
export type SchemaListMeta = components['schemas']['ListMeta'];
export type SchemaModel = components['schemas']['Model'];
export type SchemaModelAvailability = components['schemas']['ModelAvailability'];
export type SchemaModelHost = components['schemas']['ModelHost'];
export type SchemaModelOrder = components['schemas']['ModelOrder'];
export type SchemaModelResponse = components['schemas']['ModelResponse'];
export type SchemaModelResponseChunk = components['schemas']['ModelResponseChunk'];
export type SchemaModelType = components['schemas']['ModelType'];
export type SchemaMultiModalModel = components['schemas']['MultiModalModel'];
export type SchemaMultiModalResponseModel = components['schemas']['MultiModalResponseModel'];
export type SchemaRating = components['schemas']['Rating'];
export type SchemaReorderModelConfigRequest = components['schemas']['ReorderModelConfigRequest'];
export type SchemaResponseModel = components['schemas']['ResponseModel'];
export type SchemaRole = components['schemas']['Role'];
export type SchemaRootCreateModelConfigRequest =
    components['schemas']['RootCreateModelConfigRequest'];
export type SchemaRootUpdateModelConfigRequest =
    components['schemas']['RootUpdateModelConfigRequest'];
export type SchemaSort = components['schemas']['Sort'];
export type SchemaSortDirection = components['schemas']['SortDirection'];
export type SchemaStreamEndChunk = components['schemas']['StreamEndChunk'];
export type SchemaStreamStartChunk = components['schemas']['StreamStartChunk'];
export type SchemaTextOnlyResponseModel = components['schemas']['TextOnlyResponseModel'];
export type SchemaThinkingChunk = components['schemas']['ThinkingChunk'];
export type SchemaThread = components['schemas']['Thread'];
export type SchemaToolCall = components['schemas']['ToolCall'];
export type SchemaToolCallChunk = components['schemas']['ToolCallChunk'];
export type SchemaUpdateMultiModalModelConfigRequest =
    components['schemas']['UpdateMultiModalModelConfigRequest'];
export type SchemaUpdateTextOnlyModelConfigRequest =
    components['schemas']['UpdateTextOnlyModelConfigRequest'];
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
