import createFetchClient from 'openapi-fetch';
import createClient from 'openapi-react-query';

import { authMiddleware } from './authMiddleware';
import type { paths } from './v5playgroundApiSchema'; // generated by openapi-typescript

export const fetchClient = createFetchClient<paths>({
    baseUrl: process.env.VITE_API_URL,
    // This fixes an issue with openapi-fetch not cooperating with MSW
    // https://www.martinrichards.me/post/an_idiots_guide_to_msw/
    fetch: (req) => fetch(req),
});
fetchClient.use(authMiddleware);

export const queryClient = createClient(fetchClient);
