/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    '/v5/event': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Event */
        post: operations['event_v5_event_post'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v5/prompt-templates/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prompt Templates */
        get: operations['get_prompt_templates_v5_prompt_templates__get'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v5/user/whoami': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Who Am I
         * @description Get information for the current authenticated user.
         *
         *     Returns user authentication status, terms acceptance, and permissions.
         */
        get: operations['get_who_am_i_v5_user_whoami_get'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v5/user/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upsert User
         * @description Create or update a user record.
         *
         *     Accepts user info and creates or updates the user in the database.
         *     For authenticated (non-anonymous) users, also creates a HubSpot contact.
         */
        put: operations['upsert_user_v5_user__put'];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v5/user/migration': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Migrate User
         * @description Migrates annonymous user data to the logged in user account.
         *
         *     Accepts an anonymous user ID.
         */
        put: operations['migrate_user_v5_user_migration_put'];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v5/threads/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All */
        get: operations['get_all_v5_threads__get'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v5/threads/{thread_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get One With Async Attrs */
        get: operations['get_one_with_async_attrs_v5_threads__thread_id__get'];
        put?: never;
        post?: never;
        /** Delete Thread */
        delete: operations['delete_thread_v5_threads__thread_id__delete'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v5/message/{message_id}/label/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Create Label */
        put: operations['create_label_v5_message__message_id__label__put'];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v5/message/{message_id}/label/{label_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Label */
        delete: operations['delete_label_v5_message__message_id__label__label_id__delete'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v5/admin/models/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin Models */
        get: operations['get_admin_models_v5_admin_models__get'];
        /** Sort Admin Model */
        put: operations['sort_admin_model_v5_admin_models__put'];
        /** Create Admin Model */
        post: operations['create_admin_model_v5_admin_models__post'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v5/admin/models/{model_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Admin Model */
        put: operations['update_admin_model_v5_admin_models__model_id__put'];
        post?: never;
        /** Delete Admin Model */
        delete: operations['delete_admin_model_v5_admin_models__model_id__delete'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** AuthenticatedClient */
        AuthenticatedClient: {
            /** Id */
            id?: string | null;
            /** Client */
            client: string;
            /** Has Accepted Terms and Conditions */
            hasAcceptedTermsAndConditions: boolean;
            /** Has Accepted Data Collection */
            hasAcceptedDataCollection: boolean;
            /** Has Accepted Media Collection */
            hasAcceptedMediaCollection: boolean;
            /** Permissions */
            permissions?: string[];
        };
        /**
         * AvailableInfiniGramIndexId
         * @enum {string}
         */
        AvailableInfiniGramIndexId:
            | 'olmoe-0125-1b-7b'
            | 'olmo-2-0325-32b'
            | 'olmo-2-1124-13b'
            | 'olmo-3-0625-32b-think'
            | 'olmo-3-0625-32b-instruct'
            | 'olmo-3-0625-7b-instruct'
            | 'olmo-3-0625-7b-think'
            | 'pileval-llama'
            | 'tulu-3-405b'
            | 'tulu-3-70b'
            | 'tulu-3-8b';
        /** CreateMultiModalModelConfigRequest */
        CreateMultiModalModelConfigRequest: {
            /** Name */
            name: string;
            host: components['schemas']['ModelHost'];
            /** Informationurl */
            informationUrl?: string | null;
            /** Description */
            description: string;
            modelType: components['schemas']['ModelType'];
            /** Modelidonhost */
            modelIdOnHost: string;
            /**
             * Internal
             * @default true
             */
            internal?: boolean;
            /** Defaultsystemprompt */
            defaultSystemPrompt?: string | null;
            /** Familyid */
            familyId?: string | null;
            /** Familyname */
            familyName?: string | null;
            /** Availabletime */
            availableTime?: string | null;
            /** Deprecationtime */
            deprecationTime?: string | null;
            /**
             * Cancalltools
             * @default false
             */
            canCallTools?: boolean;
            /**
             * Canthink
             * @default false
             */
            canThink?: boolean;
            infiniGramIndex?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /** Temperaturedefault */
            temperatureDefault?: number | null;
            /** Temperatureupper */
            temperatureUpper?: number | null;
            /** Temperaturelower */
            temperatureLower?: number | null;
            /** Temperaturestep */
            temperatureStep?: number | null;
            /** Toppdefault */
            topPDefault?: number | null;
            /** Toppupper */
            topPUpper?: number | null;
            /** Topplower */
            topPLower?: number | null;
            /** Toppstep */
            topPStep?: number | null;
            /** Maxtokensdefault */
            maxTokensDefault?: number | null;
            /** Maxtokensupper */
            maxTokensUpper?: number | null;
            /** Maxtokenslower */
            maxTokensLower?: number | null;
            /** Maxtokensstep */
            maxTokensStep?: number | null;
            /** Stopdefault */
            stopDefault?: string[] | null;
            /**
             * Prompttype
             * @enum {string}
             */
            promptType: 'multi_modal' | 'files_only';
            /** Acceptedfiletypes */
            acceptedFileTypes: string[];
            /** Maxfilespermessage */
            maxFilesPerMessage?: number | null;
            requireFileToPrompt?: components['schemas']['FileRequiredToPromptOption'] | null;
            /** Maxtotalfilesize */
            maxTotalFileSize?: string | number | null;
            /** Allowfilesinfollowups */
            allowFilesInFollowups?: boolean | null;
            /** Id */
            id: string;
        };
        /** CreateTextOnlyModelConfigRequest */
        CreateTextOnlyModelConfigRequest: {
            /** Name */
            name: string;
            host: components['schemas']['ModelHost'];
            /** Informationurl */
            informationUrl?: string | null;
            /** Description */
            description: string;
            modelType: components['schemas']['ModelType'];
            /** Modelidonhost */
            modelIdOnHost: string;
            /**
             * Internal
             * @default true
             */
            internal?: boolean;
            /** Defaultsystemprompt */
            defaultSystemPrompt?: string | null;
            /** Familyid */
            familyId?: string | null;
            /** Familyname */
            familyName?: string | null;
            /** Availabletime */
            availableTime?: string | null;
            /** Deprecationtime */
            deprecationTime?: string | null;
            /**
             * Cancalltools
             * @default false
             */
            canCallTools?: boolean;
            /**
             * Canthink
             * @default false
             */
            canThink?: boolean;
            infiniGramIndex?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /** Temperaturedefault */
            temperatureDefault?: number | null;
            /** Temperatureupper */
            temperatureUpper?: number | null;
            /** Temperaturelower */
            temperatureLower?: number | null;
            /** Temperaturestep */
            temperatureStep?: number | null;
            /** Toppdefault */
            topPDefault?: number | null;
            /** Toppupper */
            topPUpper?: number | null;
            /** Topplower */
            topPLower?: number | null;
            /** Toppstep */
            topPStep?: number | null;
            /** Maxtokensdefault */
            maxTokensDefault?: number | null;
            /** Maxtokensupper */
            maxTokensUpper?: number | null;
            /** Maxtokenslower */
            maxTokensLower?: number | null;
            /** Maxtokensstep */
            maxTokensStep?: number | null;
            /** Stopdefault */
            stopDefault?: string[] | null;
            /**
             * Prompttype
             * @constant
             */
            promptType: 'text_only';
            /** Id */
            id: string;
        };
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: 'toolCallError';
        /**
         * ErrorSeverity
         * @enum {string}
         */
        ErrorSeverity: 'error' | 'warning' | 'info';
        /** Event */
        Event: {
            /**
             * Occurred
             * Format: date-time
             */
            occurred: string;
            /** Type */
            type: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /**
         * FileRequiredToPromptOption
         * @enum {string}
         */
        FileRequiredToPromptOption: 'first_message' | 'all_messages' | 'no_requirement';
        /**
         * FinishReason
         * @enum {string}
         */
        FinishReason:
            | 'unclosed stream'
            | 'length'
            | 'stop'
            | 'aborted'
            | 'model overloaded'
            | 'bad connection'
            | 'value error'
            | 'tool error'
            | 'unknown';
        /** FlatMessage */
        FlatMessage: {
            /** Id */
            id: string;
            /** Content */
            content: string;
            /** Inputparts */
            inputParts?: components['schemas']['Molmo2PointPart'][] | null;
            /** Creator */
            creator: string;
            role: components['schemas']['Role'];
            opts: components['schemas']['InferenceOptionsResponse'];
            /** Root */
            root: string;
            /**
             * Created
             * Format: date-time
             */
            created: string;
            /** Modelid */
            modelId: string;
            /** Modelhost */
            modelHost: string;
            /** Agentid */
            agentId?: string | null;
            /** Deleted */
            deleted?: string | null;
            /** Parent */
            parent?: string | null;
            /** Template */
            template?: string | null;
            /** Children */
            children?: string[] | null;
            /** Completion */
            completion?: string | null;
            /**
             * Final
             * @default false
             */
            final?: boolean;
            /** Original */
            original?: string | null;
            /**
             * Private
             * @default false
             */
            private?: boolean;
            modelType?: components['schemas']['ModelType'] | null;
            finishReason?: components['schemas']['FinishReason'] | null;
            /** Harmful */
            harmful?: boolean | null;
            /** Expirationtime */
            expirationTime?: string | null;
            /** Labels */
            labels?: components['schemas']['Label'][];
            /** Fileurls */
            fileUrls?: string[] | null;
            /** Toolcalls */
            toolCalls?: components['schemas']['ToolCall'][] | null;
            /** Thinking */
            thinking?: string | null;
            /** Tooldefinitions */
            toolDefinitions?: components['schemas']['ToolDefinition'][] | null;
            /** Extraparameters */
            extraParameters?: {
                [key: string]: unknown;
            } | null;
            errorCode?: components['schemas']['ErrorCode'] | null;
            /** Errordescription */
            errorDescription?: string | null;
            errorSeverity?: components['schemas']['ErrorSeverity'] | null;
            /** Snippet */
            readonly snippet: string;
            /** Islimitreached */
            readonly isLimitReached: boolean;
            /** Isolderthan30Days */
            readonly isOlderThan30Days: boolean;
        };
        /** RequestValidationError */
        HTTPValidationError: {
            /** Problem title */
            title: string;
            /** Problem type */
            type: string;
            /** Status code */
            status: number;
            errors: components['schemas']['ValidationError'][];
        };
        /** InferenceOptionsResponse */
        InferenceOptionsResponse: {
            /** Maxtokens */
            maxTokens?: number | null;
            /** Temperature */
            temperature?: number | null;
            /** Topp */
            topP?: number | null;
            /** Stop */
            stop?: string[] | null;
            /**
             * N
             * @default 1
             */
            n?: number;
            /** Logprobs */
            logprobs?: number | null;
        };
        /** Label */
        Label: {
            /** Id */
            id: string;
            /** Message */
            message: string;
            rating: components['schemas']['Rating'];
            /** Creator */
            creator: string;
            /** Comment */
            comment?: string | null;
            /**
             * Created
             * Format: date-time
             */
            created: string;
            /** Deleted */
            deleted?: string | null;
        };
        /** LabelCreateRequest */
        LabelCreateRequest: {
            /** Labels */
            labels: components['schemas']['LabelRequest'][];
        };
        /** LabelRequest */
        LabelRequest: {
            rating: components['schemas']['Rating'];
            /** Comment */
            comment?: string | null;
        };
        /** ListMeta */
        ListMeta: {
            /** Total */
            total: number;
            /** Offset */
            offset?: number | null;
            /** Limit */
            limit?: number | null;
            sort?: components['schemas']['Sort'] | null;
        };
        /**
         * ModelAvailability
         * @enum {string}
         */
        ModelAvailability: 'public' | 'internal' | 'prerelease';
        /** ModelConfigListResponse */
        ModelConfigListResponse: components['schemas']['ModelConfigResponse'][];
        /** ModelConfigResponse */
        ModelConfigResponse:
            | components['schemas']['TextOnlyModelConfigResponse']
            | components['schemas']['MultiModalModelConfigResponse'];
        /**
         * ModelHost
         * @enum {string}
         */
        ModelHost:
            | 'inferd'
            | 'modal'
            | 'beaker_queues'
            | 'cirrascale_backend'
            | 'cirrascale'
            | 'modal_openai'
            | 'test_backend'
            | 'ai2_model_hub';
        /** ModelOrder */
        ModelOrder: {
            /** Id */
            id: string;
            /** Order */
            order: number;
        };
        /**
         * ModelType
         * @enum {string}
         */
        ModelType: 'base' | 'chat';
        /** Molmo2PointPart */
        Molmo2PointPart: {
            /**
             * Type
             * @default molmo_2_input_point
             * @constant
             */
            type?: 'molmo_2_input_point';
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Time */
            time: number;
            /**
             * Label
             * @default object
             */
            label?: string;
        };
        /** MultiModalModelConfigResponse */
        MultiModalModelConfigResponse: {
            /** Id */
            id: string;
            host: components['schemas']['ModelHost'];
            /** Name */
            name: string;
            /** Informationurl */
            informationUrl?: string | null;
            /** Description */
            description: string;
            modelType: components['schemas']['ModelType'];
            /** Modelidonhost */
            modelIdOnHost: string;
            /** Internal */
            internal: boolean;
            /** Order */
            order: number;
            /** Defaultsystemprompt */
            defaultSystemPrompt?: string | null;
            /** Cancalltools */
            canCallTools: boolean;
            /** Canthink */
            canThink: boolean;
            infiniGramIndex?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /** Temperaturedefault */
            temperatureDefault: number;
            /** Temperatureupper */
            temperatureUpper: number;
            /** Temperaturelower */
            temperatureLower: number;
            /** Temperaturestep */
            temperatureStep: number;
            /** Toppdefault */
            topPDefault: number;
            /** Toppupper */
            topPUpper: number;
            /** Topplower */
            topPLower: number;
            /** Toppstep */
            topPStep: number;
            /** Maxtokensdefault */
            maxTokensDefault: number;
            /** Maxtokensupper */
            maxTokensUpper: number;
            /** Maxtokenslower */
            maxTokensLower: number;
            /** Maxtokensstep */
            maxTokensStep: number;
            /** Stopdefault */
            stopDefault?: string[] | null;
            /** Familyid */
            familyId?: string | null;
            /** Familyname */
            familyName?: string | null;
            /** Availabletime */
            availableTime?: string | null;
            /** Deprecationtime */
            deprecationTime?: string | null;
            /**
             * Createdtime
             * Format: date-time
             */
            createdTime: string;
            /**
             * Updatedtime
             * Format: date-time
             */
            updatedTime: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            promptType: 'files_only' | 'multi_modal';
            /** Acceptedfiletypes */
            acceptedFileTypes: string[];
            /** Maxfilespermessage */
            maxFilesPerMessage?: number | null;
            requireFileToPrompt?: components['schemas']['FileRequiredToPromptOption'] | null;
            /** Maxtotalfilesize */
            maxTotalFileSize?: number | null;
            /** Allowfilesinfollowups */
            allowFilesInFollowups?: boolean | null;
            readonly availability: components['schemas']['ModelAvailability'];
        };
        /** PromptTemplateResponse */
        PromptTemplateResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Content */
            content: string;
            /** Creator */
            creator: string;
            /**
             * Created
             * Format: date-time
             */
            created: string;
            /**
             * Updated
             * Format: date-time
             */
            updated: string;
            opts: components['schemas']['InferenceOptionsResponse'];
            modelType: components['schemas']['ModelType'];
            /** Fileurls */
            fileUrls: string[] | null;
            /** Tooldefinitions */
            toolDefinitions: components['schemas']['ToolDefinition'][];
            /** Extraparameters */
            extraParameters?: {
                [key: string]: unknown;
            } | null;
        };
        /** PromptTemplateResponseList */
        PromptTemplateResponseList: components['schemas']['PromptTemplateResponse'][];
        /**
         * Rating
         * @enum {integer}
         */
        Rating: -1 | 0 | 1;
        /** ReorderModelConfigRequest */
        ReorderModelConfigRequest: {
            /** Orderedmodels */
            orderedModels: components['schemas']['ModelOrder'][];
        };
        /**
         * Role
         * @enum {string}
         */
        Role: 'user' | 'assistant' | 'system' | 'tool_call_result';
        /** RootCreateModelConfigRequest */
        RootCreateModelConfigRequest:
            | components['schemas']['CreateTextOnlyModelConfigRequest']
            | components['schemas']['CreateMultiModalModelConfigRequest'];
        /** RootUpdateModelConfigRequest */
        RootUpdateModelConfigRequest:
            | components['schemas']['UpdateTextOnlyModelConfigRequest']
            | components['schemas']['UpdateMultiModalModelConfigRequest'];
        /** Sort */
        Sort: {
            /** Field */
            field: string;
            /** @default DESC */
            direction?: components['schemas']['SortDirection'];
        };
        /**
         * SortDirection
         * @enum {string}
         */
        SortDirection: 'ASC' | 'DESC';
        /** TextOnlyModelConfigResponse */
        TextOnlyModelConfigResponse: {
            /** Id */
            id: string;
            host: components['schemas']['ModelHost'];
            /** Name */
            name: string;
            /** Informationurl */
            informationUrl?: string | null;
            /** Description */
            description: string;
            modelType: components['schemas']['ModelType'];
            /** Modelidonhost */
            modelIdOnHost: string;
            /** Internal */
            internal: boolean;
            /** Order */
            order: number;
            /** Defaultsystemprompt */
            defaultSystemPrompt?: string | null;
            /** Cancalltools */
            canCallTools: boolean;
            /** Canthink */
            canThink: boolean;
            infiniGramIndex?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /** Temperaturedefault */
            temperatureDefault: number;
            /** Temperatureupper */
            temperatureUpper: number;
            /** Temperaturelower */
            temperatureLower: number;
            /** Temperaturestep */
            temperatureStep: number;
            /** Toppdefault */
            topPDefault: number;
            /** Toppupper */
            topPUpper: number;
            /** Topplower */
            topPLower: number;
            /** Toppstep */
            topPStep: number;
            /** Maxtokensdefault */
            maxTokensDefault: number;
            /** Maxtokensupper */
            maxTokensUpper: number;
            /** Maxtokenslower */
            maxTokensLower: number;
            /** Maxtokensstep */
            maxTokensStep: number;
            /** Stopdefault */
            stopDefault?: string[] | null;
            /** Familyid */
            familyId?: string | null;
            /** Familyname */
            familyName?: string | null;
            /** Availabletime */
            availableTime?: string | null;
            /** Deprecationtime */
            deprecationTime?: string | null;
            /**
             * Createdtime
             * Format: date-time
             */
            createdTime: string;
            /**
             * Updatedtime
             * Format: date-time
             */
            updatedTime: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            promptType: 'text_only';
            readonly availability: components['schemas']['ModelAvailability'];
        };
        /** Thread */
        Thread: {
            /** Id */
            id: string;
            /** Messages */
            messages: components['schemas']['FlatMessage'][];
        };
        /** ThreadList */
        ThreadList: {
            /** Threads */
            threads: components['schemas']['Thread'][];
            meta: components['schemas']['ListMeta'];
        };
        /** ToolCall */
        ToolCall: {
            /** Toolname */
            toolName: string;
            /** Args */
            args?:
                | string
                | {
                      [key: string]: unknown;
                  }
                | null;
            /** Toolcallid */
            toolCallId: string;
            toolSource: components['schemas']['ToolSource'];
        };
        /** ToolDefinition */
        ToolDefinition: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
            toolSource: components['schemas']['ToolSource'];
        };
        /**
         * ToolSource
         * @enum {string}
         */
        ToolSource: 'internal' | 'user_defined' | 'model_context_protocol';
        /** UpdateMultiModalModelConfigRequest */
        UpdateMultiModalModelConfigRequest: {
            /** Name */
            name: string;
            host: components['schemas']['ModelHost'];
            /** Informationurl */
            informationUrl?: string | null;
            /** Description */
            description: string;
            modelType: components['schemas']['ModelType'];
            /** Modelidonhost */
            modelIdOnHost: string;
            /**
             * Internal
             * @default true
             */
            internal?: boolean;
            /** Defaultsystemprompt */
            defaultSystemPrompt?: string | null;
            /** Familyid */
            familyId?: string | null;
            /** Familyname */
            familyName?: string | null;
            /** Availabletime */
            availableTime?: string | null;
            /** Deprecationtime */
            deprecationTime?: string | null;
            /**
             * Cancalltools
             * @default false
             */
            canCallTools?: boolean;
            /**
             * Canthink
             * @default false
             */
            canThink?: boolean;
            infiniGramIndex?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /** Temperaturedefault */
            temperatureDefault?: number | null;
            /** Temperatureupper */
            temperatureUpper?: number | null;
            /** Temperaturelower */
            temperatureLower?: number | null;
            /** Temperaturestep */
            temperatureStep?: number | null;
            /** Toppdefault */
            topPDefault?: number | null;
            /** Toppupper */
            topPUpper?: number | null;
            /** Topplower */
            topPLower?: number | null;
            /** Toppstep */
            topPStep?: number | null;
            /** Maxtokensdefault */
            maxTokensDefault?: number | null;
            /** Maxtokensupper */
            maxTokensUpper?: number | null;
            /** Maxtokenslower */
            maxTokensLower?: number | null;
            /** Maxtokensstep */
            maxTokensStep?: number | null;
            /** Stopdefault */
            stopDefault?: string[] | null;
            /**
             * Prompttype
             * @enum {string}
             */
            promptType: 'multi_modal' | 'files_only';
            /** Acceptedfiletypes */
            acceptedFileTypes: string[];
            /** Maxfilespermessage */
            maxFilesPerMessage?: number | null;
            requireFileToPrompt?: components['schemas']['FileRequiredToPromptOption'] | null;
            /** Maxtotalfilesize */
            maxTotalFileSize?: string | number | null;
            /** Allowfilesinfollowups */
            allowFilesInFollowups?: boolean | null;
        };
        /** UpdateTextOnlyModelConfigRequest */
        UpdateTextOnlyModelConfigRequest: {
            /** Name */
            name: string;
            host: components['schemas']['ModelHost'];
            /** Informationurl */
            informationUrl?: string | null;
            /** Description */
            description: string;
            modelType: components['schemas']['ModelType'];
            /** Modelidonhost */
            modelIdOnHost: string;
            /**
             * Internal
             * @default true
             */
            internal?: boolean;
            /** Defaultsystemprompt */
            defaultSystemPrompt?: string | null;
            /** Familyid */
            familyId?: string | null;
            /** Familyname */
            familyName?: string | null;
            /** Availabletime */
            availableTime?: string | null;
            /** Deprecationtime */
            deprecationTime?: string | null;
            /**
             * Cancalltools
             * @default false
             */
            canCallTools?: boolean;
            /**
             * Canthink
             * @default false
             */
            canThink?: boolean;
            infiniGramIndex?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /** Temperaturedefault */
            temperatureDefault?: number | null;
            /** Temperatureupper */
            temperatureUpper?: number | null;
            /** Temperaturelower */
            temperatureLower?: number | null;
            /** Temperaturestep */
            temperatureStep?: number | null;
            /** Toppdefault */
            topPDefault?: number | null;
            /** Toppupper */
            topPUpper?: number | null;
            /** Topplower */
            topPLower?: number | null;
            /** Toppstep */
            topPStep?: number | null;
            /** Maxtokensdefault */
            maxTokensDefault?: number | null;
            /** Maxtokensupper */
            maxTokensUpper?: number | null;
            /** Maxtokenslower */
            maxTokensLower?: number | null;
            /** Maxtokensstep */
            maxTokensStep?: number | null;
            /** Stopdefault */
            stopDefault?: string[] | null;
            /**
             * Prompttype
             * @constant
             */
            promptType: 'text_only';
        };
        /** UpsertUserRequest */
        UpsertUserRequest: {
            /** Id */
            id?: string | null;
            /** Termsaccepteddate */
            termsAcceptedDate?: string | null;
            /** Acceptancerevokeddate */
            acceptanceRevokedDate?: string | null;
            /** Datacollectionaccepteddate */
            dataCollectionAcceptedDate?: string | null;
            /** Datacollectionacceptancerevokeddate */
            dataCollectionAcceptanceRevokedDate?: string | null;
            /** Mediacollectionaccepteddate */
            mediaCollectionAcceptedDate?: string | null;
            /** Mediacollectionacceptancerevokeddate */
            mediaCollectionAcceptanceRevokedDate?: string | null;
        };
        /** UpsertUserResponse */
        UpsertUserResponse: {
            /** Id */
            id: string;
            /** Client */
            client: string;
            /** Termsaccepteddate */
            termsAcceptedDate?: string | null;
            /** Acceptancerevokeddate */
            acceptanceRevokedDate?: string | null;
            /** Datacollectionaccepteddate */
            dataCollectionAcceptedDate?: string | null;
            /** Datacollectionacceptancerevokeddate */
            dataCollectionAcceptanceRevokedDate?: string | null;
            /** Mediacollectionaccepteddate */
            mediaCollectionAcceptedDate?: string | null;
            /** Mediacollectionacceptancerevokeddate */
            mediaCollectionAcceptanceRevokedDate?: string | null;
        };
        /** User */
        User: {
            /** Id */
            id?: string;
            /** Client */
            client: string;
            /**
             * Termsaccepteddate
             * Format: date-time
             */
            termsAcceptedDate: string;
            /** Acceptancerevokeddate */
            acceptanceRevokedDate: string | null;
            /** Datacollectionaccepteddate */
            dataCollectionAcceptedDate: string | null;
            /** Datacollectionacceptancerevokeddate */
            dataCollectionAcceptanceRevokedDate: string | null;
            /** Mediacollectionaccepteddate */
            mediaCollectionAcceptedDate: string | null;
            /** Mediacollectionacceptancerevokeddate */
            mediaCollectionAcceptanceRevokedDate: string | null;
        };
        /** UserMigrationRequest */
        UserMigrationRequest: {
            /** Anonymoususerid */
            anonymousUserId: string;
        };
        /** UserMigrationResponse */
        UserMigrationResponse: {
            updatedUser: components['schemas']['User'] | null;
            /** Messagesupdatedcount */
            messagesUpdatedCount: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Problem */
        Problem: {
            /** Problem title */
            title: string;
            /** Problem type */
            type: string;
            /** Status code */
            status: number;
            /** Problem detail */
            detail?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type SchemaAuthenticatedClient = components['schemas']['AuthenticatedClient'];
export type SchemaAvailableInfiniGramIndexId = components['schemas']['AvailableInfiniGramIndexId'];
export type SchemaCreateMultiModalModelConfigRequest =
    components['schemas']['CreateMultiModalModelConfigRequest'];
export type SchemaCreateTextOnlyModelConfigRequest =
    components['schemas']['CreateTextOnlyModelConfigRequest'];
export type SchemaErrorCode = components['schemas']['ErrorCode'];
export type SchemaErrorSeverity = components['schemas']['ErrorSeverity'];
export type SchemaEvent = components['schemas']['Event'];
export type SchemaFileRequiredToPromptOption = components['schemas']['FileRequiredToPromptOption'];
export type SchemaFinishReason = components['schemas']['FinishReason'];
export type SchemaFlatMessage = components['schemas']['FlatMessage'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaInferenceOptionsResponse = components['schemas']['InferenceOptionsResponse'];
export type SchemaLabel = components['schemas']['Label'];
export type SchemaLabelCreateRequest = components['schemas']['LabelCreateRequest'];
export type SchemaLabelRequest = components['schemas']['LabelRequest'];
export type SchemaListMeta = components['schemas']['ListMeta'];
export type SchemaModelAvailability = components['schemas']['ModelAvailability'];
export type SchemaModelConfigListResponse = components['schemas']['ModelConfigListResponse'];
export type SchemaModelConfigResponse = components['schemas']['ModelConfigResponse'];
export type SchemaModelHost = components['schemas']['ModelHost'];
export type SchemaModelOrder = components['schemas']['ModelOrder'];
export type SchemaModelType = components['schemas']['ModelType'];
export type SchemaMolmo2PointPart = components['schemas']['Molmo2PointPart'];
export type SchemaMultiModalModelConfigResponse =
    components['schemas']['MultiModalModelConfigResponse'];
export type SchemaPromptTemplateResponse = components['schemas']['PromptTemplateResponse'];
export type SchemaPromptTemplateResponseList = components['schemas']['PromptTemplateResponseList'];
export type SchemaRating = components['schemas']['Rating'];
export type SchemaReorderModelConfigRequest = components['schemas']['ReorderModelConfigRequest'];
export type SchemaRole = components['schemas']['Role'];
export type SchemaRootCreateModelConfigRequest =
    components['schemas']['RootCreateModelConfigRequest'];
export type SchemaRootUpdateModelConfigRequest =
    components['schemas']['RootUpdateModelConfigRequest'];
export type SchemaSort = components['schemas']['Sort'];
export type SchemaSortDirection = components['schemas']['SortDirection'];
export type SchemaTextOnlyModelConfigResponse =
    components['schemas']['TextOnlyModelConfigResponse'];
export type SchemaThread = components['schemas']['Thread'];
export type SchemaThreadList = components['schemas']['ThreadList'];
export type SchemaToolCall = components['schemas']['ToolCall'];
export type SchemaToolDefinition = components['schemas']['ToolDefinition'];
export type SchemaToolSource = components['schemas']['ToolSource'];
export type SchemaUpdateMultiModalModelConfigRequest =
    components['schemas']['UpdateMultiModalModelConfigRequest'];
export type SchemaUpdateTextOnlyModelConfigRequest =
    components['schemas']['UpdateTextOnlyModelConfigRequest'];
export type SchemaUpsertUserRequest = components['schemas']['UpsertUserRequest'];
export type SchemaUpsertUserResponse = components['schemas']['UpsertUserResponse'];
export type SchemaUser = components['schemas']['User'];
export type SchemaUserMigrationRequest = components['schemas']['UserMigrationRequest'];
export type SchemaUserMigrationResponse = components['schemas']['UserMigrationResponse'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type SchemaProblem = components['schemas']['Problem'];
export type $defs = Record<string, never>;
export interface operations {
    event_v5_event_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['Event'];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': boolean;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    get_prompt_templates_v5_prompt_templates__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['PromptTemplateResponseList'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    get_who_am_i_v5_user_whoami_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['AuthenticatedClient'];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    upsert_user_v5_user__put: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['UpsertUserRequest'];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['UpsertUserResponse'] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    migrate_user_v5_user_migration_put: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['UserMigrationRequest'];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['UserMigrationResponse'];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    get_all_v5_threads__get: {
        parameters: {
            query?: {
                offset?: number | null;
                limit?: number;
                sort?: string | null;
                order?: components['schemas']['SortDirection'];
            };
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ThreadList'];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    get_one_with_async_attrs_v5_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['Thread'];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    delete_thread_v5_threads__thread_id__delete: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    create_label_v5_message__message_id__label__put: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['LabelCreateRequest'];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['FlatMessage'];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    delete_label_v5_message__message_id__label__label_id__delete: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path: {
                message_id: string;
                label_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    get_admin_models_v5_admin_models__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ModelConfigListResponse'];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    sort_admin_model_v5_admin_models__put: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['ReorderModelConfigRequest'];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    create_admin_model_v5_admin_models__post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['RootCreateModelConfigRequest'];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ModelConfigResponse'];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    update_admin_model_v5_admin_models__model_id__put: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['RootUpdateModelConfigRequest'];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ModelConfigResponse'] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    delete_admin_model_v5_admin_models__model_id__delete: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
}
type ReadonlyArray<T> = [Exclude<T, undefined>] extends [any[]]
    ? Readonly<Exclude<T, undefined>>
    : Readonly<Exclude<T, undefined>[]>;
export const availableInfiniGramIndexIdValues: ReadonlyArray<
    components['schemas']['AvailableInfiniGramIndexId']
> = [
    'olmoe-0125-1b-7b',
    'olmo-2-0325-32b',
    'olmo-2-1124-13b',
    'olmo-3-0625-32b-think',
    'olmo-3-0625-32b-instruct',
    'olmo-3-0625-7b-instruct',
    'olmo-3-0625-7b-think',
    'pileval-llama',
    'tulu-3-405b',
    'tulu-3-70b',
    'tulu-3-8b',
];
export const createMultiModalModelConfigRequestPromptTypeValues: ReadonlyArray<
    components['schemas']['CreateMultiModalModelConfigRequest']['promptType']
> = ['multi_modal', 'files_only'];
export const errorCodeValues: ReadonlyArray<components['schemas']['ErrorCode']> = ['toolCallError'];
export const errorSeverityValues: ReadonlyArray<components['schemas']['ErrorSeverity']> = [
    'error',
    'warning',
    'info',
];
export const fileRequiredToPromptOptionValues: ReadonlyArray<
    components['schemas']['FileRequiredToPromptOption']
> = ['first_message', 'all_messages', 'no_requirement'];
export const finishReasonValues: ReadonlyArray<components['schemas']['FinishReason']> = [
    'unclosed stream',
    'length',
    'stop',
    'aborted',
    'model overloaded',
    'bad connection',
    'value error',
    'tool error',
    'unknown',
];
export const modelAvailabilityValues: ReadonlyArray<components['schemas']['ModelAvailability']> = [
    'public',
    'internal',
    'prerelease',
];
export const modelHostValues: ReadonlyArray<components['schemas']['ModelHost']> = [
    'inferd',
    'modal',
    'beaker_queues',
    'cirrascale_backend',
    'cirrascale',
    'modal_openai',
    'test_backend',
    'ai2_model_hub',
];
export const modelTypeValues: ReadonlyArray<components['schemas']['ModelType']> = ['base', 'chat'];
export const multiModalModelConfigResponsePromptTypeValues: ReadonlyArray<
    components['schemas']['MultiModalModelConfigResponse']['promptType']
> = ['files_only', 'multi_modal'];
export const ratingValues: ReadonlyArray<components['schemas']['Rating']> = [-1, 0, 1];
export const roleValues: ReadonlyArray<components['schemas']['Role']> = [
    'user',
    'assistant',
    'system',
    'tool_call_result',
];
export const sortDirectionValues: ReadonlyArray<components['schemas']['SortDirection']> = [
    'ASC',
    'DESC',
];
export const textOnlyModelConfigResponsePromptTypeValues: ReadonlyArray<
    components['schemas']['TextOnlyModelConfigResponse']['promptType']
> = ['text_only'];
export const toolSourceValues: ReadonlyArray<components['schemas']['ToolSource']> = [
    'internal',
    'user_defined',
    'model_context_protocol',
];
export const updateMultiModalModelConfigRequestPromptTypeValues: ReadonlyArray<
    components['schemas']['UpdateMultiModalModelConfigRequest']['promptType']
> = ['multi_modal', 'files_only'];
