/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    '/v5/event': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Event */
        post: operations['event_v5_event_post'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v5/prompt-templates/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prompt Templates */
        get: operations['get_prompt_templates_v5_prompt_templates__get'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v5/user/whoami': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User
         * @description Get information for the current authenticated user.
         *
         *     Previously known as /whoami in the Flask API.
         *     Returns user authentication status, terms acceptance, and permissions.
         */
        get: operations['get_user_v5_user_whoami_get'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v5/admin/models/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Admin Models */
        get: operations['get_admin_models_v5_admin_models__get'];
        /** Sort Admin Model */
        put: operations['sort_admin_model_v5_admin_models__put'];
        /** Create Admin Model */
        post: operations['create_admin_model_v5_admin_models__post'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v5/admin/models/{model_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Admin Model */
        put: operations['update_admin_model_v5_admin_models__model_id__put'];
        post?: never;
        /** Delete Admin Model */
        delete: operations['delete_admin_model_v5_admin_models__model_id__delete'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** AuthenticatedClient */
        AuthenticatedClient: {
            /** Id */
            id?: string | null;
            /** Client */
            client: string;
            /** Hasacceptedtermsandconditions */
            hasAcceptedTermsAndConditions: boolean;
            /** Hasaccepteddatacollection */
            hasAcceptedDataCollection: boolean;
            /** Hasacceptedmediacollection */
            hasAcceptedMediaCollection: boolean;
            /** Permissions */
            permissions?: string[];
        };
        /**
         * AvailableInfiniGramIndexId
         * @enum {string}
         */
        AvailableInfiniGramIndexId:
            | 'olmoe-0125-1b-7b'
            | 'olmo-2-0325-32b'
            | 'olmo-2-1124-13b'
            | 'olmo-3-0625-32b-think'
            | 'olmo-3-0625-32b-instruct'
            | 'olmo-3-0625-7b-instruct'
            | 'olmo-3-0625-7b-think'
            | 'pileval-llama'
            | 'tulu-3-405b'
            | 'tulu-3-70b'
            | 'tulu-3-8b';
        /** CreateMultiModalModelConfigRequest */
        CreateMultiModalModelConfigRequest: {
            /** Name */
            name: string;
            host: components['schemas']['ModelHost'];
            /** Informationurl */
            informationUrl?: string | null;
            /** Description */
            description: string;
            modelType: components['schemas']['ModelType'];
            /** Modelidonhost */
            modelIdOnHost: string;
            /**
             * Internal
             * @default true
             */
            internal?: boolean;
            /** Defaultsystemprompt */
            defaultSystemPrompt?: string | null;
            /** Familyid */
            familyId?: string | null;
            /** Familyname */
            familyName?: string | null;
            /** Availabletime */
            availableTime?: string | null;
            /** Deprecationtime */
            deprecationTime?: string | null;
            /**
             * Cancalltools
             * @default false
             */
            canCallTools?: boolean;
            /**
             * Canthink
             * @default false
             */
            canThink?: boolean;
            infiniGramIndex?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /** Temperaturedefault */
            temperatureDefault?: number | null;
            /** Temperatureupper */
            temperatureUpper?: number | null;
            /** Temperaturelower */
            temperatureLower?: number | null;
            /** Temperaturestep */
            temperatureStep?: number | null;
            /** Toppdefault */
            topPDefault?: number | null;
            /** Toppupper */
            topPUpper?: number | null;
            /** Topplower */
            topPLower?: number | null;
            /** Toppstep */
            topPStep?: number | null;
            /** Maxtokensdefault */
            maxTokensDefault?: number | null;
            /** Maxtokensupper */
            maxTokensUpper?: number | null;
            /** Maxtokenslower */
            maxTokensLower?: number | null;
            /** Maxtokensstep */
            maxTokensStep?: number | null;
            /** Stopdefault */
            stopDefault?: string[] | null;
            /**
             * Prompttype
             * @enum {string}
             */
            promptType: 'multi_modal' | 'files_only';
            /** Acceptedfiletypes */
            acceptedFileTypes: string[];
            /** Maxfilespermessage */
            maxFilesPerMessage?: number | null;
            requireFileToPrompt?: components['schemas']['FileRequiredToPromptOption'] | null;
            /** Maxtotalfilesize */
            maxTotalFileSize?: string | number | null;
            /** Allowfilesinfollowups */
            allowFilesInFollowups?: boolean | null;
            /** Id */
            id: string;
        };
        /** CreateTextOnlyModelConfigRequest */
        CreateTextOnlyModelConfigRequest: {
            /** Name */
            name: string;
            host: components['schemas']['ModelHost'];
            /** Informationurl */
            informationUrl?: string | null;
            /** Description */
            description: string;
            modelType: components['schemas']['ModelType'];
            /** Modelidonhost */
            modelIdOnHost: string;
            /**
             * Internal
             * @default true
             */
            internal?: boolean;
            /** Defaultsystemprompt */
            defaultSystemPrompt?: string | null;
            /** Familyid */
            familyId?: string | null;
            /** Familyname */
            familyName?: string | null;
            /** Availabletime */
            availableTime?: string | null;
            /** Deprecationtime */
            deprecationTime?: string | null;
            /**
             * Cancalltools
             * @default false
             */
            canCallTools?: boolean;
            /**
             * Canthink
             * @default false
             */
            canThink?: boolean;
            infiniGramIndex?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /** Temperaturedefault */
            temperatureDefault?: number | null;
            /** Temperatureupper */
            temperatureUpper?: number | null;
            /** Temperaturelower */
            temperatureLower?: number | null;
            /** Temperaturestep */
            temperatureStep?: number | null;
            /** Toppdefault */
            topPDefault?: number | null;
            /** Toppupper */
            topPUpper?: number | null;
            /** Topplower */
            topPLower?: number | null;
            /** Toppstep */
            topPStep?: number | null;
            /** Maxtokensdefault */
            maxTokensDefault?: number | null;
            /** Maxtokensupper */
            maxTokensUpper?: number | null;
            /** Maxtokenslower */
            maxTokensLower?: number | null;
            /** Maxtokensstep */
            maxTokensStep?: number | null;
            /** Stopdefault */
            stopDefault?: string[] | null;
            /**
             * Prompttype
             * @constant
             */
            promptType: 'text_only';
            /** Id */
            id: string;
        };
        /** Event */
        Event: {
            /**
             * Occurred
             * Format: date-time
             */
            occurred: string;
            /** Type */
            type: string;
            /** Details */
            details: {
                [key: string]: unknown;
            };
        };
        /**
         * FileRequiredToPromptOption
         * @enum {string}
         */
        FileRequiredToPromptOption: 'first_message' | 'all_messages' | 'no_requirement';
        /** RequestValidationError */
        HTTPValidationError: {
            /** Problem title */
            title: string;
            /** Problem type */
            type: string;
            /** Status code */
            status: number;
            errors: components['schemas']['ValidationError'][];
        };
        /** InferenceOptionsResponse */
        InferenceOptionsResponse: {
            /** Maxtokens */
            maxTokens?: number | null;
            /** Temperature */
            temperature?: number | null;
            /** Topp */
            topP?: number | null;
            /** Stop */
            stop?: string[] | null;
            /**
             * N
             * @default 1
             */
            n?: number;
            /** Logprobs */
            logprobs?: number | null;
        };
        /**
         * ModelAvailability
         * @enum {string}
         */
        ModelAvailability: 'public' | 'internal' | 'prerelease';
        /** ModelConfigListResponse */
        ModelConfigListResponse: components['schemas']['ModelConfigResponse'][];
        /** ModelConfigResponse */
        ModelConfigResponse:
            | components['schemas']['TextOnlyModelConfigResponse']
            | components['schemas']['MultiModalModelConfigResponse'];
        /**
         * ModelHost
         * @enum {string}
         */
        ModelHost:
            | 'inferd'
            | 'modal'
            | 'beaker_queues'
            | 'cirrascale_backend'
            | 'cirrascale'
            | 'modal_openai'
            | 'test_backend'
            | 'ai2_model_hub';
        /** ModelOrder */
        ModelOrder: {
            /** Id */
            id: string;
            /** Order */
            order: number;
        };
        /**
         * ModelType
         * @enum {string}
         */
        ModelType: 'base' | 'chat';
        /** MultiModalModelConfigResponse */
        MultiModalModelConfigResponse: {
            /** Id */
            id: string;
            host: components['schemas']['ModelHost'];
            /** Name */
            name: string;
            /** Informationurl */
            informationUrl?: string | null;
            /** Description */
            description: string;
            modelType: components['schemas']['ModelType'];
            /** Modelidonhost */
            modelIdOnHost: string;
            /** Internal */
            internal: boolean;
            /** Order */
            order: number;
            /** Defaultsystemprompt */
            defaultSystemPrompt?: string | null;
            /** Cancalltools */
            canCallTools: boolean;
            /** Canthink */
            canThink: boolean;
            infiniGramIndex?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /** Temperaturedefault */
            temperatureDefault: number;
            /** Temperatureupper */
            temperatureUpper: number;
            /** Temperaturelower */
            temperatureLower: number;
            /** Temperaturestep */
            temperatureStep: number;
            /** Toppdefault */
            topPDefault: number;
            /** Toppupper */
            topPUpper: number;
            /** Topplower */
            topPLower: number;
            /** Toppstep */
            topPStep: number;
            /** Maxtokensdefault */
            maxTokensDefault: number;
            /** Maxtokensupper */
            maxTokensUpper: number;
            /** Maxtokenslower */
            maxTokensLower: number;
            /** Maxtokensstep */
            maxTokensStep: number;
            /** Stopdefault */
            stopDefault?: string[] | null;
            /** Familyid */
            familyId?: string | null;
            /** Familyname */
            familyName?: string | null;
            /** Availabletime */
            availableTime?: string | null;
            /** Deprecationtime */
            deprecationTime?: string | null;
            /**
             * Createdtime
             * Format: date-time
             */
            createdTime: string;
            /**
             * Updatedtime
             * Format: date-time
             */
            updatedTime: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            promptType: 'files_only' | 'multi_modal';
            /** Acceptedfiletypes */
            acceptedFileTypes: string[];
            /** Maxfilespermessage */
            maxFilesPerMessage?: number | null;
            requireFileToPrompt?: components['schemas']['FileRequiredToPromptOption'] | null;
            /** Maxtotalfilesize */
            maxTotalFileSize?: number | null;
            /** Allowfilesinfollowups */
            allowFilesInFollowups?: boolean | null;
            readonly availability: components['schemas']['ModelAvailability'];
        };
        /** PromptTemplateResponse */
        PromptTemplateResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Content */
            content: string;
            /** Creator */
            creator: string;
            /**
             * Created
             * Format: date-time
             */
            created: string;
            /**
             * Updated
             * Format: date-time
             */
            updated: string;
            opts: components['schemas']['InferenceOptionsResponse'];
            modelType: components['schemas']['ModelType'];
            /** Fileurls */
            fileUrls: string[] | null;
            /** Tooldefinitions */
            toolDefinitions: components['schemas']['ToolDefinition'][];
            /** Extraparameters */
            extraParameters?: {
                [key: string]: unknown;
            } | null;
        };
        /** PromptTemplateResponseList */
        PromptTemplateResponseList: components['schemas']['PromptTemplateResponse'][];
        /** ReorderModelConfigRequest */
        ReorderModelConfigRequest: {
            /** Orderedmodels */
            orderedModels: components['schemas']['ModelOrder'][];
        };
        /** RootCreateModelConfigRequest */
        RootCreateModelConfigRequest:
            | components['schemas']['CreateTextOnlyModelConfigRequest']
            | components['schemas']['CreateMultiModalModelConfigRequest'];
        /** RootUpdateModelConfigRequest */
        RootUpdateModelConfigRequest:
            | components['schemas']['UpdateTextOnlyModelConfigRequest']
            | components['schemas']['UpdateMultiModalModelConfigRequest'];
        /** TextOnlyModelConfigResponse */
        TextOnlyModelConfigResponse: {
            /** Id */
            id: string;
            host: components['schemas']['ModelHost'];
            /** Name */
            name: string;
            /** Informationurl */
            informationUrl?: string | null;
            /** Description */
            description: string;
            modelType: components['schemas']['ModelType'];
            /** Modelidonhost */
            modelIdOnHost: string;
            /** Internal */
            internal: boolean;
            /** Order */
            order: number;
            /** Defaultsystemprompt */
            defaultSystemPrompt?: string | null;
            /** Cancalltools */
            canCallTools: boolean;
            /** Canthink */
            canThink: boolean;
            infiniGramIndex?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /** Temperaturedefault */
            temperatureDefault: number;
            /** Temperatureupper */
            temperatureUpper: number;
            /** Temperaturelower */
            temperatureLower: number;
            /** Temperaturestep */
            temperatureStep: number;
            /** Toppdefault */
            topPDefault: number;
            /** Toppupper */
            topPUpper: number;
            /** Topplower */
            topPLower: number;
            /** Toppstep */
            topPStep: number;
            /** Maxtokensdefault */
            maxTokensDefault: number;
            /** Maxtokensupper */
            maxTokensUpper: number;
            /** Maxtokenslower */
            maxTokensLower: number;
            /** Maxtokensstep */
            maxTokensStep: number;
            /** Stopdefault */
            stopDefault?: string[] | null;
            /** Familyid */
            familyId?: string | null;
            /** Familyname */
            familyName?: string | null;
            /** Availabletime */
            availableTime?: string | null;
            /** Deprecationtime */
            deprecationTime?: string | null;
            /**
             * Createdtime
             * Format: date-time
             */
            createdTime: string;
            /**
             * Updatedtime
             * Format: date-time
             */
            updatedTime: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            promptType: 'text_only';
            readonly availability: components['schemas']['ModelAvailability'];
        };
        /** ToolDefinition */
        ToolDefinition: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
            toolSource: components['schemas']['ToolSource'];
        };
        /**
         * ToolSource
         * @enum {string}
         */
        ToolSource: 'internal' | 'user_defined' | 'model_context_protocol';
        /** UpdateMultiModalModelConfigRequest */
        UpdateMultiModalModelConfigRequest: {
            /** Name */
            name: string;
            host: components['schemas']['ModelHost'];
            /** Informationurl */
            informationUrl?: string | null;
            /** Description */
            description: string;
            modelType: components['schemas']['ModelType'];
            /** Modelidonhost */
            modelIdOnHost: string;
            /**
             * Internal
             * @default true
             */
            internal?: boolean;
            /** Defaultsystemprompt */
            defaultSystemPrompt?: string | null;
            /** Familyid */
            familyId?: string | null;
            /** Familyname */
            familyName?: string | null;
            /** Availabletime */
            availableTime?: string | null;
            /** Deprecationtime */
            deprecationTime?: string | null;
            /**
             * Cancalltools
             * @default false
             */
            canCallTools?: boolean;
            /**
             * Canthink
             * @default false
             */
            canThink?: boolean;
            infiniGramIndex?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /** Temperaturedefault */
            temperatureDefault?: number | null;
            /** Temperatureupper */
            temperatureUpper?: number | null;
            /** Temperaturelower */
            temperatureLower?: number | null;
            /** Temperaturestep */
            temperatureStep?: number | null;
            /** Toppdefault */
            topPDefault?: number | null;
            /** Toppupper */
            topPUpper?: number | null;
            /** Topplower */
            topPLower?: number | null;
            /** Toppstep */
            topPStep?: number | null;
            /** Maxtokensdefault */
            maxTokensDefault?: number | null;
            /** Maxtokensupper */
            maxTokensUpper?: number | null;
            /** Maxtokenslower */
            maxTokensLower?: number | null;
            /** Maxtokensstep */
            maxTokensStep?: number | null;
            /** Stopdefault */
            stopDefault?: string[] | null;
            /**
             * Prompttype
             * @enum {string}
             */
            promptType: 'multi_modal' | 'files_only';
            /** Acceptedfiletypes */
            acceptedFileTypes: string[];
            /** Maxfilespermessage */
            maxFilesPerMessage?: number | null;
            requireFileToPrompt?: components['schemas']['FileRequiredToPromptOption'] | null;
            /** Maxtotalfilesize */
            maxTotalFileSize?: string | number | null;
            /** Allowfilesinfollowups */
            allowFilesInFollowups?: boolean | null;
        };
        /** UpdateTextOnlyModelConfigRequest */
        UpdateTextOnlyModelConfigRequest: {
            /** Name */
            name: string;
            host: components['schemas']['ModelHost'];
            /** Informationurl */
            informationUrl?: string | null;
            /** Description */
            description: string;
            modelType: components['schemas']['ModelType'];
            /** Modelidonhost */
            modelIdOnHost: string;
            /**
             * Internal
             * @default true
             */
            internal?: boolean;
            /** Defaultsystemprompt */
            defaultSystemPrompt?: string | null;
            /** Familyid */
            familyId?: string | null;
            /** Familyname */
            familyName?: string | null;
            /** Availabletime */
            availableTime?: string | null;
            /** Deprecationtime */
            deprecationTime?: string | null;
            /**
             * Cancalltools
             * @default false
             */
            canCallTools?: boolean;
            /**
             * Canthink
             * @default false
             */
            canThink?: boolean;
            infiniGramIndex?: components['schemas']['AvailableInfiniGramIndexId'] | null;
            /** Temperaturedefault */
            temperatureDefault?: number | null;
            /** Temperatureupper */
            temperatureUpper?: number | null;
            /** Temperaturelower */
            temperatureLower?: number | null;
            /** Temperaturestep */
            temperatureStep?: number | null;
            /** Toppdefault */
            topPDefault?: number | null;
            /** Toppupper */
            topPUpper?: number | null;
            /** Topplower */
            topPLower?: number | null;
            /** Toppstep */
            topPStep?: number | null;
            /** Maxtokensdefault */
            maxTokensDefault?: number | null;
            /** Maxtokensupper */
            maxTokensUpper?: number | null;
            /** Maxtokenslower */
            maxTokensLower?: number | null;
            /** Maxtokensstep */
            maxTokensStep?: number | null;
            /** Stopdefault */
            stopDefault?: string[] | null;
            /**
             * Prompttype
             * @constant
             */
            promptType: 'text_only';
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Problem */
        Problem: {
            /** Problem title */
            title: string;
            /** Problem type */
            type: string;
            /** Status code */
            status: number;
            /** Problem detail */
            detail?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type SchemaAuthenticatedClient = components['schemas']['AuthenticatedClient'];
export type SchemaAvailableInfiniGramIndexId = components['schemas']['AvailableInfiniGramIndexId'];
export type SchemaCreateMultiModalModelConfigRequest =
    components['schemas']['CreateMultiModalModelConfigRequest'];
export type SchemaCreateTextOnlyModelConfigRequest =
    components['schemas']['CreateTextOnlyModelConfigRequest'];
export type SchemaEvent = components['schemas']['Event'];
export type SchemaFileRequiredToPromptOption = components['schemas']['FileRequiredToPromptOption'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaInferenceOptionsResponse = components['schemas']['InferenceOptionsResponse'];
export type SchemaModelAvailability = components['schemas']['ModelAvailability'];
export type SchemaModelConfigListResponse = components['schemas']['ModelConfigListResponse'];
export type SchemaModelConfigResponse = components['schemas']['ModelConfigResponse'];
export type SchemaModelHost = components['schemas']['ModelHost'];
export type SchemaModelOrder = components['schemas']['ModelOrder'];
export type SchemaModelType = components['schemas']['ModelType'];
export type SchemaMultiModalModelConfigResponse =
    components['schemas']['MultiModalModelConfigResponse'];
export type SchemaPromptTemplateResponse = components['schemas']['PromptTemplateResponse'];
export type SchemaPromptTemplateResponseList = components['schemas']['PromptTemplateResponseList'];
export type SchemaReorderModelConfigRequest = components['schemas']['ReorderModelConfigRequest'];
export type SchemaRootCreateModelConfigRequest =
    components['schemas']['RootCreateModelConfigRequest'];
export type SchemaRootUpdateModelConfigRequest =
    components['schemas']['RootUpdateModelConfigRequest'];
export type SchemaTextOnlyModelConfigResponse =
    components['schemas']['TextOnlyModelConfigResponse'];
export type SchemaToolDefinition = components['schemas']['ToolDefinition'];
export type SchemaToolSource = components['schemas']['ToolSource'];
export type SchemaUpdateMultiModalModelConfigRequest =
    components['schemas']['UpdateMultiModalModelConfigRequest'];
export type SchemaUpdateTextOnlyModelConfigRequest =
    components['schemas']['UpdateTextOnlyModelConfigRequest'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type SchemaProblem = components['schemas']['Problem'];
export type $defs = Record<string, never>;
export interface operations {
    event_v5_event_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['Event'];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': boolean;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    get_prompt_templates_v5_prompt_templates__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['PromptTemplateResponseList'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    get_user_v5_user_whoami_get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['AuthenticatedClient'];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    get_admin_models_v5_admin_models__get: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ModelConfigListResponse'];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    sort_admin_model_v5_admin_models__put: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['ReorderModelConfigRequest'];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    create_admin_model_v5_admin_models__post: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['RootCreateModelConfigRequest'];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ModelConfigResponse'];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    update_admin_model_v5_admin_models__model_id__put: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['RootUpdateModelConfigRequest'];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ModelConfigResponse'] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
    delete_admin_model_v5_admin_models__model_id__delete: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string | null;
                'X-Anonymous-User-ID'?: string | null;
            };
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['HTTPValidationError'];
                };
            };
            /** @description Client Error */
            '4XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
            /** @description Server Error */
            '5XX': {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/problem+json': components['schemas']['Problem'];
                };
            };
        };
    };
}
type ReadonlyArray<T> = [Exclude<T, undefined>] extends [any[]]
    ? Readonly<Exclude<T, undefined>>
    : Readonly<Exclude<T, undefined>[]>;
export const availableInfiniGramIndexIdValues: ReadonlyArray<
    components['schemas']['AvailableInfiniGramIndexId']
> = [
    'olmoe-0125-1b-7b',
    'olmo-2-0325-32b',
    'olmo-2-1124-13b',
    'olmo-3-0625-32b-think',
    'olmo-3-0625-32b-instruct',
    'olmo-3-0625-7b-instruct',
    'olmo-3-0625-7b-think',
    'pileval-llama',
    'tulu-3-405b',
    'tulu-3-70b',
    'tulu-3-8b',
];
export const createMultiModalModelConfigRequestPromptTypeValues: ReadonlyArray<
    components['schemas']['CreateMultiModalModelConfigRequest']['promptType']
> = ['multi_modal', 'files_only'];
export const fileRequiredToPromptOptionValues: ReadonlyArray<
    components['schemas']['FileRequiredToPromptOption']
> = ['first_message', 'all_messages', 'no_requirement'];
export const modelAvailabilityValues: ReadonlyArray<components['schemas']['ModelAvailability']> = [
    'public',
    'internal',
    'prerelease',
];
export const modelHostValues: ReadonlyArray<components['schemas']['ModelHost']> = [
    'inferd',
    'modal',
    'beaker_queues',
    'cirrascale_backend',
    'cirrascale',
    'modal_openai',
    'test_backend',
    'ai2_model_hub',
];
export const modelTypeValues: ReadonlyArray<components['schemas']['ModelType']> = ['base', 'chat'];
export const multiModalModelConfigResponsePromptTypeValues: ReadonlyArray<
    components['schemas']['MultiModalModelConfigResponse']['promptType']
> = ['files_only', 'multi_modal'];
export const textOnlyModelConfigResponsePromptTypeValues: ReadonlyArray<
    components['schemas']['TextOnlyModelConfigResponse']['promptType']
> = ['text_only'];
export const toolSourceValues: ReadonlyArray<components['schemas']['ToolSource']> = [
    'internal',
    'user_defined',
    'model_context_protocol',
];
export const updateMultiModalModelConfigRequestPromptTypeValues: ReadonlyArray<
    components['schemas']['UpdateMultiModalModelConfigRequest']['promptType']
> = ['multi_modal', 'files_only'];
