import createFetchClient from 'openapi-fetch';
import createClient from 'openapi-react-query';

import type { paths } from './v1'; // generated by openapi-typescript

const olmoApiClient = createFetchClient<paths>({
    baseUrl: process.env.LLMX_API,
});

export const olmoApiQueryClient = createClient(olmoApiClient);
