import createFetchClient, { type Middleware } from 'openapi-fetch';
import createClient from 'openapi-react-query';

import { auth0Client } from '@/api/auth/auth0Client';

import { ANONYMOUS_USER_ID_KEY } from '../ClientBase';
import type { paths } from './v1'; // generated by openapi-typescript

const authMiddleware: Middleware = {
    async onRequest({ request }) {
        const token = await auth0Client.getToken();
        if (token) {
            request.headers.set('Authorization', `Bearer ${token}`);
        } else {
            const anonymousUserId = window.localStorage.getItem(ANONYMOUS_USER_ID_KEY);

            if (anonymousUserId) {
                request.headers.set('X-Anonymous-User-ID', anonymousUserId);
            }
        }
    },
};

export const olmoApiClient = createFetchClient<paths>({
    baseUrl: process.env.LLMX_API_URL,
});
olmoApiClient.use(authMiddleware);

export const $olmoApiQueryClient = createClient(olmoApiClient);
