import createFetchClient from 'openapi-fetch';
import createClient from 'openapi-react-query';

import type { paths } from './v1'; // generated by openapi-typescript

export const olmoApiClient = createFetchClient<paths>({
    baseUrl: process.env.LLMX_API_URL,
});

export const $olmoApiQueryClient = createClient(olmoApiClient);
