/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/v3/attribution': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get CorpusLink spans and documents from a prompt */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description A GetAttributionRequest */
            requestBody: {
                content: {
                    'application/json': components['schemas']['GetAttributionRequest'];
                };
            };
            responses: {
                /** @description Empty Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v3/message/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream a prompt response */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description A CreateMessageRequestV3 */
            requestBody: {
                content: {
                    'application/json': components['schemas']['CreateMessageRequestV3'];
                };
            };
            responses: {
                /** @description Empty Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v3/message/stream': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream a prompt response */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description A CreateMessageRequestV3 */
            requestBody: {
                content: {
                    'application/json': components['schemas']['CreateMessageRequestV3'];
                };
            };
            responses: {
                /** @description Empty Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v4/message/stream': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream a prompt response */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description A CreateMessageRequestV4 */
            requestBody: {
                content: {
                    'application/json': components['schemas']['CreateMessageRequestV4'];
                };
            };
            responses: {
                /** @description Empty Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v4/models/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get available models and their configuration */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Empty Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ResponseModel'][];
                    };
                };
            };
        };
        /** Reorder models */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description A ReorderModelConfigRequest */
            requestBody: {
                content: {
                    'application/json': components['schemas']['ReorderModelConfigRequest'];
                };
            };
            responses: {
                /** @description Empty Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Add a new model */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description A CreateModelConfigRequest */
            requestBody: {
                content: {
                    'application/json': components['schemas']['CreateModelConfigRequest'];
                };
            };
            responses: {
                /** @description A ResponseModel */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ResponseModel'];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/v4/models/{model_id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a model */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    model_id: string;
                };
                cookie?: never;
            };
            /** @description A UpdateTextOnlyModelConfigRequest or UpdateMultiModalModelConfigRequest */
            requestBody: {
                content: {
                    'application/json':
                        | components['schemas']['UpdateTextOnlyModelConfigRequest']
                        | components['schemas']['UpdateMultiModalModelConfigRequest'];
                };
            };
            responses: {
                /** @description A ResponseModel */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': components['schemas']['ResponseModel'];
                    };
                };
            };
        };
        post?: never;
        /** Delete a model */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    model_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Empty Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateMessageRequestV3 */
        CreateMessageRequestV3: {
            /**
             * Captchatoken
             * @default null
             */
            captchaToken: string | null;
            /** Content */
            content: string;
            /** Host */
            host: string;
            /** Model */
            model: string;
            opts?: components['schemas']['InferenceOpts'];
            /**
             * Original
             * @default null
             */
            original: string | null;
            /**
             * Parent
             * @default null
             */
            parent: string | null;
            /**
             * Private
             * @default false
             */
            private: boolean;
            /** @default user */
            role: components['schemas']['Role'] | null;
            /**
             * Template
             * @default null
             */
            template: string | null;
        };
        /** CreateMessageRequestV4 */
        CreateMessageRequestV4: {
            /**
             * Captchatoken
             * @default null
             */
            captchaToken: string | null;
            /** Content */
            content: string;
            /** Host */
            host: string;
            /**
             * Logprobs
             * @default null
             */
            logprobs: number | null;
            /**
             * Maxtokens
             * @default 2048
             */
            maxTokens: number;
            /** Model */
            model: string;
            /**
             * N
             * @default 1
             */
            n: number;
            /**
             * Original
             * @default null
             */
            original: string | null;
            /**
             * Parent
             * @default null
             */
            parent: string | null;
            /**
             * Private
             * @default false
             */
            private: boolean;
            /** @default user */
            role: components['schemas']['Role'] | null;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
            /**
             * Template
             * @default null
             */
            template: string | null;
            /**
             * Topp
             * @default 1
             */
            topP: number;
        };
        /** CreateModelConfigRequest */
        CreateModelConfigRequest: {
            /**
             * Availabletime
             * @default null
             */
            availableTime: string | null;
            /**
             * Defaultsystemprompt
             * @default null
             */
            defaultSystemPrompt: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            deprecationTime: string | null;
            /** Description */
            description: string;
            /**
             * Familyid
             * @default null
             */
            familyId: string | null;
            /**
             * Familyname
             * @default null
             */
            familyName: string | null;
            host: components['schemas']['ModelHost'];
            /** Id */
            id: string;
            /**
             * Internal
             * @default true
             */
            internal: boolean;
            /** Modelidonhost */
            modelIdOnHost: string;
            modelType: components['schemas']['ModelType'];
            /** Name */
            name: string;
            promptType: components['schemas']['PromptType'];
        };
        /**
         * FileRequiredToPromptOption
         * @enum {string}
         */
        FileRequiredToPromptOption: 'first_message' | 'all_messages' | 'no_requirement';
        /** GetAttributionRequest */
        GetAttributionRequest: {
            /**
             * Maxdisplaycontextlength
             * @default 250
             */
            maxDisplayContextLength: number;
            /**
             * Maxdocuments
             * @default 10
             */
            maxDocuments: number;
            /** Modelid */
            modelId: string;
            /** Modelresponse */
            modelResponse: string;
            /** Prompt */
            prompt: string;
        };
        /** InferenceOpts */
        InferenceOpts: {
            /**
             * Logprobs
             * @default null
             */
            logprobs: number | null;
            /**
             * Max Tokens
             * @default 2048
             */
            max_tokens: number;
            /**
             * N
             * @default 1
             */
            n: number;
            /**
             * Stop
             * @default null
             */
            stop: string[] | null;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
            /**
             * Top P
             * @default 1
             */
            top_p: number;
        };
        /**
         * ModelHost
         * @enum {string}
         */
        ModelHost: 'inferd' | 'modal';
        /** ModelOrder */
        ModelOrder: {
            /** Id */
            id: string;
            /** Order */
            order: number;
        };
        /**
         * ModelType
         * @enum {string}
         */
        ModelType: 'base' | 'chat';
        /**
         * PromptType
         * @enum {string}
         */
        PromptType: 'text_only' | 'multi_modal';
        /** ReorderModelConfigRequest */
        ReorderModelConfigRequest: {
            /** Orderedmodels */
            orderedModels: components['schemas']['ModelOrder'][];
        };
        /** ResponseModel */
        ResponseModel: {
            /**
             * Availabletime
             * @default null
             */
            availableTime: string | null;
            /**
             * Createdtime
             * Format: date-time
             */
            createdTime: string;
            /**
             * Defaultsystemprompt
             * @default null
             */
            defaultSystemPrompt: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            deprecationTime: string | null;
            /** Description */
            description: string;
            /**
             * Familyid
             * @default null
             */
            familyId: string | null;
            /**
             * Familyname
             * @default null
             */
            familyName: string | null;
            /** Host */
            host: string;
            /** Id */
            id: string;
            /** Internal */
            internal: boolean;
            /** Modelidonhost */
            modelIdOnHost: string;
            modelType: components['schemas']['ModelType'];
            /** Name */
            name: string;
            /** Order */
            order: number;
            promptType: components['schemas']['PromptType'];
            /**
             * Updatedtime
             * Format: date-time
             */
            updatedTime: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: 'user' | 'assistant' | 'system';
        /** UpdateMultiModalModelConfigRequest */
        UpdateMultiModalModelConfigRequest: {
            /** Acceptedfiletypes */
            acceptedFileTypes: string[];
            /**
             * Allowfilesinfollowups
             * @default null
             */
            allowFilesInFollowups: boolean | null;
            /**
             * Availabletime
             * @default null
             */
            availableTime: string | null;
            /**
             * Defaultsystemprompt
             * @default null
             */
            defaultSystemPrompt: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            deprecationTime: string | null;
            /** Description */
            description: string;
            /**
             * Familyid
             * @default null
             */
            familyId: string | null;
            /**
             * Familyname
             * @default null
             */
            familyName: string | null;
            host: components['schemas']['ModelHost'];
            /**
             * Internal
             * @default true
             */
            internal: boolean;
            /**
             * Maxfilespermessage
             * @default null
             */
            maxFilesPerMessage: number | null;
            /**
             * Maxtotalfilesize
             * @default null
             */
            maxTotalFileSize: number | null;
            /** Modelidonhost */
            modelIdOnHost: string;
            modelType: components['schemas']['ModelType'];
            /** Name */
            name: string;
            /**
             * Prompttype
             * @constant
             */
            promptType: 'multi_modal';
            /** @default null */
            requireFileToPrompt: components['schemas']['FileRequiredToPromptOption'] | null;
        };
        /** UpdateTextOnlyModelConfigRequest */
        UpdateTextOnlyModelConfigRequest: {
            /**
             * Availabletime
             * @default null
             */
            availableTime: string | null;
            /**
             * Defaultsystemprompt
             * @default null
             */
            defaultSystemPrompt: string | null;
            /**
             * Deprecationtime
             * @default null
             */
            deprecationTime: string | null;
            /** Description */
            description: string;
            /**
             * Familyid
             * @default null
             */
            familyId: string | null;
            /**
             * Familyname
             * @default null
             */
            familyName: string | null;
            host: components['schemas']['ModelHost'];
            /**
             * Internal
             * @default true
             */
            internal: boolean;
            /** Modelidonhost */
            modelIdOnHost: string;
            modelType: components['schemas']['ModelType'];
            /** Name */
            name: string;
            /**
             * Prompttype
             * @constant
             */
            promptType: 'text_only';
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
