name: Unit Tests

concurrency:
  group: unit-${{ github.ref }}
  cancel-in-progress: true

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: lts/*
          cache: 'yarn'
      - run: yarn install
      - run: yarn test